Program PGIMajVer;

uses
  Fiche {Agl7\Mac7\Fiche.pas},
  FichGrid {Agl7\Mac7\FichGrid.pas},
  FichList {Agl7\Mac7\FichList.pas},
  Forms {Agl7\Mac7\Forms.pas'},
  GRS1 {Agl7\Mac7\GRS1.pas},
  Hent1 {Agl7\Mac7\Hent1.pas},
  MenuOlg {Agl7\Mac7\MenuOlg.pas},
  Mul {Agl7\Mac7\Mul.pas},
  SplashG {Agl7\Mac7\SplashG.pas},
  Tablette {Agl7\Mac7\Tablette.pas},
  AccesPortail_TOF in '..\Lib\AccesPortail_TOF.pas',
  AdressePiece in '..\..\Gescom\Lib\ADRESSEPIECE.PAS' {FAdrPiece},
  AfInitSoc in '..\..\Gescom\LibA\AfInitSoc.pas',
  AglInitCommun in '..\Lib\AGLINITCOMMUN.PAS',
  AGLInitGC in '..\..\Gescom\Lib\AGLInitGC.pas',
  AJOUTSOCRGT_TOF in '..\Lib\AJOUTSOCRGT_TOF.PAS',
  ArticleEdit_TOF in '..\..\Gescom\Lib\ArticleEdit_TOF.pas',
  ARTPHOTO_TOF in '..\..\Gescom\LibM\ARTPHOTO_TOF.pas',
  AssistContreMVtoA in '..\..\Gescom\Lib\ASSISTCONTREMVTOA.PAS' {FCmdeContreM},
  ASSISTINITSOC in '..\Lib\ASSISTINITSOC.PAS' {FAssistInitSoc},
  BackupRestore_TOF in '..\Lib\BackupRestore_TOF.pas',
  BalSit in '..\..\Compta\LibN\BalSit.pas',
  BasculeArticleLie in '..\..\Gescom\Lib\BasculeArticleLie.pas',
  BUNDLEDETAIL_TOF in '..\Lib\BUNDLEDETAIL_TOF.PAS',
  Calcole in '..\..\Compta\Lib4\Calcole.pas',
  CalcOLEGescom in '..\..\Gescom\Lib\CalcOLEGescom.pas',
  CalculSuggestion in '..\..\Gescom\Lib\CalculSuggestion.pas',
  CasEmplois in '..\..\Gescom\Lib\CASEMPLOIS.PAS' {FCasEmplois},
  CdeOuv in '..\..\Gescom\Lib\CDEOUV.PAS',
  ChoixDupNomen in '..\..\Gescom\Lib\ChoixDupNomen.pas',
  CLgCpte in '..\..\Compta\LibC\CLgCpte.pas',
  Cloture in '..\..\Compta\LibC\Cloture.pas',
  CodeAFB in '..\..\Compta\Lib4\CodeAFB.pas',
  CodeSect in '..\..\Compta\LibC\CODESECT.PAS' {FCodesect},
  Commun in '..\..\Treso\Lib\COMMUN.PAS',
  ConfidentAffaire in '..\..\Gescom\LibA\CONFIDENTAFFAIRE.PAS',
  Confidentialite_TOF in '..\Lib\CONFIDENTIALITE_TOF.PAS',
  Constantes in '..\..\Treso\Lib\CONSTANTES.PAS',
  CORRESP_TOM in '..\..\Compta\LibN\CORRESP_TOM.PAS',
  CpAxe_Tom in '..\..\Compta\LibN\CpAxe_Tom.pas',
  CPCHANCELL_TOF in '..\..\Compta\LibN\CPCHANCELL_TOF.pas',
  CPCODEPOSTAL_TOF in '..\..\Compta\LibN\CPCODEPOSTAL_TOF.PAS',
  CPGENERAUX_TOM in '..\..\Compta\Lib4\CPGENERAUX_TOM.PAS',
  CPJOURNAL_TOM in '..\..\Compta\Lib4\CPJOURNAL_TOM.pas',
  CPREGION_TOF in '..\..\Compta\LibN\CPREGION_TOF.PAS',
  CPSECTION_TOM in '..\..\Compta\Lib4\CPSECTION_TOM.PAS',
  CPSTRUCTURE_TOF in '..\..\Compta\LibN\CPSTRUCTURE_TOF.PAS',
  CptaDiff in '..\..\Gescom\Lib\CPTADIFF.PAS',
  CpteUtil in '..\..\Compta\Lib4\CpteUtil.pas',
  CPTIERS_TOM in '..\..\Compta\Lib4\CPTIERS_TOM.PAS',
  CPVENTILTYPECROIS_TOF in '..\..\Compta\LibN\CPVENTILTYPECROIS_TOF.pas',
  CreePieceOle in '..\..\Gescom\Lib\CREEPIECEOLE.PAS',
  CRITEDT in '..\..\Compta\LibC\CRITEDT.PAS',
  ctiAlerte in '..\Lib\CTIALERTE.PAS' {FCtiAlerte},
  ctiConst in '..\Lib\CTICONST.PAS',
  ctiInterface in '..\Lib\CTIINTERFACE.PAS',
  DebitSurListe_Tof in '..\..\Gescom\Lib\DEBITSURLISTE_TOF.PAS',
  DepotUtil in '..\..\Gescom\Lib\DepotUtil.pas',
  DEVISE_TOM in '..\..\Compta\LibN\DEVISE_TOM.pas',
  DicoAf in '..\..\Gescom\LibA\DicoAf.pas',
  Dispo in '..\..\Gescom\Lib\Dispo.PAS',
  DispoDetail in '..\..\Gescom\Lib\DISPODETAIL.PAS',
  DISPODETAIL_TOM in '..\..\Gescom\Lib\DISPODETAIL_TOM.PAS',
  DiversCommunTOT in '..\Lib\DiversCommunTOT.pas',
  DUPLICNOMEN_TOF in '..\..\Gescom\Lib\DUPLICNOMEN_TOF.PAS',
  EBizUtil in '..\..\Gescom\LibEC\EBizUtil.pas',
  Echeance in '..\..\Compta\LibC\ECHEANCE.PAS' {FEcheance},
  ECRPIECE_TOF in '..\Lib\ECRPIECE_TOF.PAS',
  EDIT_TARIF_TOF in '..\..\Gescom\Lib\EDIT_TARIF_TOF.PAS',
  EdtLegal in '..\..\Compta\LibC\EdtLegal.pas',
  EmplacementUtil in '..\..\Gescom\Lib\EmplacementUtil.pas',
  Ent1 in '..\..\Compta\Lib4\Ent1.pas',
  EntGC in '..\Lib\ENTGC.PAS',
  ENTGP in '..\..\Gescom\LibW\ENTGP.PAS',
  EntPGI in '..\Lib\ENTPGI.PAS',
  EntRT in '..\..\Prospect\Lib\ENTRT.PAS',
  EnvironnementUtil in '..\Lib\EnvironnementUtil.pas',
  EtbMce in '..\..\Compta\LibL\EtbMce.pas',
  EuroPGI in '..\Lib\EuroPGI.pas',
  eventDecla in '..\Lib\eventDecla.pas',
  Exercice in '..\..\Compta\Lib4\Exercice.pas',
  FactAdresse in '..\..\Gescom\Lib\FACTADRESSE.PAS',
  FactArticle in '..\..\Gescom\Lib\FACTARTICLE.PAS',
  factcalc in '..\..\Gescom\Lib\FACTCALC.PAS',
  FactComm in '..\..\Gescom\Lib\FactComm.pas',
  FactCompl in '..\..\Gescom\Lib\FACTCOMPL.PAS',
  FACTCONSIGNE in '..\..\Gescom\Lib\FACTCONSIGNE.PAS',
  FactContreM in '..\..\Gescom\Lib\FactContreM.pas',
  FactCpta in '..\..\Gescom\Lib\FactCpta.pas',
  FactEche in '..\..\Gescom\Lib\FACTECHE.PAS',
  FactFiltreLigne in '..\..\Gescom\Lib\FactFiltreLigne.pas',
  FactFormule in '..\..\Gescom\Lib\FACTFORMULE.PAS',
  FactGrp in '..\..\Gescom\Lib\FactGrp.pas',
  FactLien in '..\..\Gescom\Lib\FactLien.pas',
  FactLigneFrais in '..\..\Gescom\Lib\FactLigneFrais.pas',
  FactMarche in '..\..\Gescom\Lib\FACTMARCHE.PAS',
  FactNomen in '..\..\Gescom\Lib\FactNomen.pas',
  FactPiece in '..\..\Gescom\Lib\FACTPIECE.PAS',
  FactPieceContainer in '..\..\Gescom\Lib\FactPieceContainer.pas',
  FactRg in '..\..\Gescom\Lib\FactRg.pas',
  FactSpec in '..\..\Gescom\Lib\FACTSPEC.PAS',
  FactStock in '..\..\Gescom\Lib\FACTSTOCK.PAS',
  FactTarifs in '..\..\Gescom\Lib\FactTarifs.pas',
  FactTiers in '..\..\Gescom\Lib\FACTTIERS.PAS',
  FactTOB in '..\..\Gescom\Lib\FACTTOB.PAS',
  FactTriLigne in '..\..\Gescom\Lib\FactTriLigne.pas',
  Facture in '..\..\Gescom\Lib\Facture.pas' {FFacture},
  FactUtil in '..\..\Gescom\Lib\FactUtil.pas',
  FactVariante in '..\..\Gescom\Lib\FactVariante.pas',
  FichComm in '..\Lib\FichComm.pas',
  galFileTools in '..\..\CegidPGI\Lib\galFileTools.pas',
  galSystem in '..\..\CEGIDPGI\Lib\GALSYSTEM.PAS',
  gcCdeOuv_Tof in '..\..\Gescom\Lib\gcCdeOuv_Tof.pas',
  GcColisage in '..\..\Gescom\Lib\GcColisage.pas',
  GcColisageAutomatique in '..\..\Gescom\Lib\GcColisageAutomatique.pas',
  GcComplPrix_tof in '..\..\Gescom\Lib\GcComplPrix_tof.pas',
  GCControleFacture_Tof in '..\..\Gescom\Lib\GCCONTROLEFACTURE_TOF.PAS',
  GCEXPORT_IMMO_TOF in '..\..\Gescom\Lib\GCEXPORT_IMMO_TOF.PAS',
  gcFiltreLigne in '..\..\Gescom\Lib\GCFILTRELIGNE.PAS' {FFiltreLigne},
  GcFonctionVar_Tof in '..\..\Gescom\Lib\GCFONCTIONVAR_TOF.PAS',
  GCGenerik_Radio_Tof in '..\..\Gescom\Lib\GCGENERIK_RADIO_TOF.PAS',
  gcLienPiece in '..\..\Gescom\Lib\GCLIENPIECE.PAS' {dgcLienPiece},
  GCOuvertureGEP in '..\..\Gescom\Lib\GCOuvertureGEP.pas',
  GcPrepaExpAfcMul_TOF in '..\..\Gescom\Lib\GcPrepaExpAfcMul_Tof.pas',
  GcPrepaExpe in '..\..\Gescom\Lib\GCPREPAEXPE.PAS',
  GcPrixRevientAchat in '..\..\Gescom\Lib\GcPrixRevientAchat.pas',
  GcStkCoherence in '..\..\Gescom\Lib\GCSTKCOHERENCE.PAS' {StkCoherence},
  GcStkDispatch in '..\..\Gescom\Lib\GcStkDispatch.pas',
  GCSTKNomenclature_TOF in '..\..\Gescom\Lib\GCSTKNomenclature_TOF.pas',
  GcStkPicking in '..\..\Gescom\Lib\GcStkPicking.pas' {fStkPicking},
  gcStkPrixArc_TOF in '..\..\Gescom\Lib\GCSTKPRIXARC_TOF.PAS',
  GcStkRecalcul in '..\..\Gescom\Lib\GCSTKRECALCUL.PAS',
  GCstkValo in '..\..\Gescom\Lib\GCSTKVALO.PAS',
  GCStkValoParam_TOF in '..\..\Gescom\Lib\GCStkValoParam_TOF.PAS',
  GCStkValoParam_TOM in '..\..\Gescom\Lib\GCStkValoParam_TOM.PAS',
  GCStkValoType_TOF in '..\..\Gescom\Lib\GCStkValoType_TOF.PAS',
  GCStkValoType_TOM in '..\..\Gescom\Lib\GCStkValoType_TOM.PAS',
  gcTransfoCdeOuv_Tof in '..\..\Gescom\Lib\gcTransfoCdeOuv_Tof.pas',
  gcTriLigne in '..\..\Gescom\Lib\GCTRILIGNE.PAS' {FTriLigne},
  gcVerifPiece in '..\..\Gescom\Lib\GCVERIFPIECE.PAS' {VerifPiece},
  GenereContreM in '..\..\Gescom\Lib\GenereContreM.pas',
  GerePiece in '..\..\Gescom\Lib\GEREPIECE.PAS',
  GereTobInterne in '..\..\Gescom\LibA\GereTobInterne.pas',
  Hcompte in '..\..\Compta\Lib4\HCOMPTE.PAS' {FZoom},
  HistorisePiece_Tof in '..\..\Gescom\Lib\HistorisePiece_Tof.pas',
  HManifest in '..\Lib\HManifest.pas',
  HRegCpte in '..\..\Compta\Lib4\HREGCPTE.PAS',
  HZoomSP in '..\..\Compta\Lib4\HZOOMSP.PAS' {FZoomSP},
  ImpactTiersPiece in '..\..\Gescom\Lib\ImpactTiersPiece.pas',
  ImportObjetLot_TOF in '..\Lib\ImportObjetLot_TOF.pas',
  ImpPrefG in '..\..\Compta\LibC\ImpPrefG.pas' {FImporPRef},
  IndiceArticle in '..\..\Gescom\Lib\IndiceArticle.PAS',
  InvUtil in '..\..\Gescom\Lib\InvUtil.pas',
  KPMGUTIL in '..\..\Prospect\Lib\KPMGUTIL.PAS',
  LetBatch in '..\..\Compta\LibC\LetBatch.pas',
  LettAuto in '..\Lib\Lettauto.pas',
  LettUtil in '..\..\Compta\LibC\LETTUTIL.PAS',
  LGCOMPTE_TOF in '..\..\Compta\LibN\LGCOMPTE_TOF.PAS',
  LIGNEFRAIS_TOF in '..\..\Gescom\Lib\LIGNEFRAIS_TOF.PAS',
  LigNomen in '..\..\Gescom\Lib\LIGNOMEN.PAS' {FLigNomen},
  ListUsersAutorises in '..\Lib\ListUsersAutorises.pas',
  MajEnRafale in '..\Lib\MajEnRafale.PAS',
  MajHalley in '..\Lib\MajHalley.pas',
  MajHalleyProc in '..\Lib\MajHalleyProc.pas',
  MajHalleyUtil in '..\Lib\MajHalleyUtil.pas',
  MajSocParLot_TOF in '..\Lib\MajSocParLot_TOF.PAS',
  MDispAdm in '..\Lib\MDispAdm.pas' {gctie: TDataModule},
  Mea_Tom in '..\..\Gescom\Lib\Mea_Tom.pas',
  MeaUtil in '..\..\Gescom\Lib\MEAUTIL.PAS',
  MessagesErreur in '..\..\Gescom\Lib\MESSAGESERREUR.PAS',
  MulGene in '..\..\Compta\LibC\MulGene.pas',
  MulJal in '..\..\Compta\LibC\MulJal.pas',
  MulSecti in '..\..\Compta\LibC\MulSecti.pas',
  MulTiers in '..\..\Compta\LibC\MulTiers.pas',
  NomenErr in '..\..\Gescom\Lib\NOMENERR.PAS' {FNomenErr},
  NomenLig in '..\..\Gescom\Lib\NOMENLIG.PAS' {FNomenLig},
  NomenUtil in '..\..\Gescom\Lib\NOMENUTIL.PAS',
  OptionDuplic_TOF in '..\..\Gescom\Lib\OptionDuplic_TOF.pas',
  OuvreExo in '..\..\Compta\LibC\OuvreExo.pas',
  ParaClo in '..\..\Compta\LibC\ParaClo.pas',
  PgDADSCommun in '..\..\Paie\Lib\PgDADSCommun.pas',
  PlateFormeMul_TOF in '..\..\Gescom\Lib\PlateFormeMul_TOF.pas',
  PlateFormePiece_TOF in '..\..\Gescom\Lib\PlateFormePiece_TOF.pas',
  QR in '..\..\Compta\Lib4\QR.pas',
  QRJDivis in '..\..\Compta\LibC\QRJDivis.pas',
  QRRupt in '..\..\Compta\LibC\QRRupt.pas',
  R_DE_RUB in '..\..\Compta\LibN\R_DE_RUB.pas',
  RapSuppr in '..\..\Compta\LibC\RapSuppr.pas',
  ResulSuggestion in '..\..\Gescom\Lib\RESULSUGGESTION.PAS' {FResulSuggestion},
  SaisComm in '..\..\Compta\LibC\SAISCOMM.PAS',
  SAISUTIL in '..\..\Compta\Lib4\SAISUTIL.PAS',
  SelectDocSuggestion in '..\..\Gescom\Lib\SelectDocSuggestion.pas',
  SoldeCpt in '..\..\Compta\LibC\SoldeCpt.pas',
  SOUCHE_TOM in '..\..\Compta\Lib4\SOUCHE_TOM.PAS',
  Soussect in '..\..\Compta\LibC\Soussect.pas',
  STKFICHETRACE in '..\..\Gescom\Lib\STKFICHETRACE.PAS',
  StkFormule in '..\..\Gescom\Lib\STKFORMULE.PAS',
  StkMoulinette in '..\..\Gescom\Lib\STKMOULINETTE.PAS',
  StkMouvement in '..\..\Gescom\Lib\STKMOUVEMENT.PAS',
  STKMOUVEMENT_TOM in '..\..\Gescom\Lib\STKMOUVEMENT_TOM.PAS',
  StkNature in '..\..\Gescom\Lib\StkNature.PAS',
  StockUtil in '..\..\Gescom\Lib\STOCKUTIL.PAS',
  SuprGene in '..\..\Compta\LibC\SuprGene.pas',
  SuprJal in '..\..\Compta\LibC\SuprJal.pas',
  TabLiEdt in '..\..\Compta\LibC\TabLiEdt.pas',
  TarifCond in '..\..\Gescom\Lib\TARIFCOND.PAS' {FTarifCond},
  TarifUtil in '..\..\Gescom\Lib\TarifUtil.pas',
  tCalcCum in '..\..\Compta\Lib4\tCalcCum.pas',
  TiersPayeur in '..\..\Compta\LibC\TiersPayeur.pas',
  TiersUtil in '..\Lib\TIERSUTIL.PAS',
  TImpFic in '..\..\Compta\LibC\TIMPFIC.PAS',
  TomAgence in '..\..\treso\Lib\TomAgence.pas',
  TomCalendrier in '..\..\treso\Lib\TomCalendrier.pas',
  TomIdentificationBancaire in '..\Lib\TomIdentificationBancaire.pas',
  TomProfilUser in '..\..\Compta\LibN\TOMPROFILUSER.PAS',
  TraitePiece in '..\..\Gescom\Lib\TraitePiece.pas',
  Transfert in '..\..\Gescom\Lib\TRANSFERT.PAS' {FTransfert},
  TriTabLi in '..\..\Compta\LibC\TriTabLi.pas',
  TVA in '..\..\Compta\Lib4\TVA.pas',
  TVAEtab in '..\..\Compta\Lib4\TVAETAB.PAS' {FTvaEtab},
  UDimArticle in '..\..\Gescom\Lib\UDimArticle.pas',
  ULibAnalytique in '..\..\Compta\LibC\ULIBANALYTIQUE.PAS',
  uLibCalcEdtCompta in '..\..\Compta\LibN\uLibCalcEdtCompta.pas',
  ULIBCLOTURE in '..\..\Compta\LibN\ULIBCLOTURE.pas',
  ULibEcriture in '..\..\Compta\LibC\ULIBECRITURE.PAS',
  ULibExercice in '..\..\Compta\LibC\ULibExercice.pas',
  ULibIdentBancaire in '..\Lib\ULIBIDENTBANCAIRE.PAS',
  uLibRevision in '..\..\Compta\LibN\ULIBREVISION.PAS',
  ULibTrSynchro in '..\..\Compta\LibN\ULibTrSynchro.pas',
  ULibWindows in '..\..\Compta\LibC\ULibWindows.pas',
  UObjFiltres in '..\..\treso\Lib\UObjFiltres.pas',
  UProcGen in '..\..\Treso\Lib\UPROCGEN.PAS',
  uRecupSQLModele in '..\Lib\uRecupSQLModele.pas',
  UserGrp_tom in '..\Lib\USERGRP_TOM.PAS',
  uTablesGed in '..\Lib\uTablesGed.pas',
  UtilAction in '..\..\Prospect\Lib\UTILACTION.PAS',
  UtilAlertes in '..\Lib\UTILALERTES.PAS',
  UtilArticle in '..\..\Gescom\Lib\UTILARTICLE.PAS',
  UtilCB in '..\Lib\utilCB.pas',
  UtilChainage in '..\..\prospect\Lib\UtilChainage.pas',
  UtilConfid in '..\..\Gescom\Lib\UTILCONFID.PAS',
  UtilCtiAlerte in '..\Lib\UTILCTIALERTE.PAS',
  UtilDimArticle in '..\..\Gescom\Lib\UtilDimArticle.pas',
  UtilDispGC in '..\..\Gescom\Lib\UtilDispGC.pas',
  UtilEdt in '..\..\Compta\LibC\UtilEdt.pas',
  UtilFO in '..\..\Gescom\Lib\UtilFO.pas',
  UTilFonctionCalcul in '..\..\Gescom\Lib\UTilFonctionCalcul.pas',
  UtilGA in '..\..\Gescom\LibA\UTILGA.PAS',
  UtilGC in '..\..\Gescom\Lib\UTILGC.PAS',
  UtilGrp in '..\..\Gescom\Lib\UTILGRP.PAS',
  UtilInterCompta in '..\..\Gescom\Lib\UtilInterCompta.pas',
  UtilLien in '..\Lib\UtilLien.pas',
  UtilMulTrt in '..\..\Gescom\LibA\UtilMulTrt.pas',
  UtilOracle in '..\Lib\UtilOracle.pas',
  utilPGI in '..\Lib\UTILPGI.PAS',
  UtilRessource in '..\..\Gescom\LibA\UtilRessource.pas',
  UTILRT in '..\..\Prospect\Lib\UTILRT.PAS',
  UtilSais in '..\..\Compta\Lib4\UtilSais.pas',
  UTilSelection in '..\..\Prospect\lib\UtilSelection.pas',
  UtilSoc in '..\Lib\UTILSOC.PAS',
  UtilTarif in '..\..\Gescom\Lib\UtilTarif.pas',
  UtilTauxNeg in '..\..\Gescom\Lib\UtilTauxNeg.pas',
  utofAfBaseCodeAffaire in '..\..\Gescom\LibA\utofAfBaseCodeAffaire.pas',
  UTOFAFTRADUCCHAMPLIBRE in '..\..\Gescom\LibA\UTOFAFTRADUCCHAMPLIBRE.PAS',
  UtofBTMemorisation in '..\..\Gescom\Lib\UtofBTMemorisation.pas',
  UTofCegidLibreTiersCom in '..\..\Gescom\Lib\UTofCegidLibreTiersCom.pas',
  UTofCegidPCI in '..\..\Gescom\Lib\UTofCegidPCI.pas',
  uTOFComm in '..\Lib\uTOFComm.PAS',
  UtofExportConfidentialite in '..\..\Prospect\Lib\UtofExportConfidentialite.pas',
  UtofGCAcomptes in '..\..\Gescom\Lib\UTOFGCACOMPTES.PAS',
  UTofGcmulCatalog_Rech in '..\..\Gescom\Lib\UTofGcmulCatalog_Rech.pas',
  UTOFGRILLEFILTRE in '..\..\Compta\LibN\UTOFGRILLEFILTRE.PAS',
  UtofMBOParamDim in '..\..\Gescom\LibM\UtofMBOParamDim.pas',
  UTOFMBOVALIDEMODELE in '..\..\Gescom\LibM\UTOFMBOVALIDEMODELE.PAS',
  UTofOptionEdit in '..\..\Gescom\Lib\UTofOptionEdit.pas',
  UTofPiedPort in '..\..\Gescom\Lib\UTOFPIEDPORT.PAS',
  UtofRess_Occup in '..\..\prospect\Lib\UTofRess_Occup.pas',
  UtofRessource_Mul in '..\..\Gescom\LibA\UtofRessource_Mul.pas',
  UtofTiersCTI_Mul in '..\..\Prospect\Lib\UtofTiersCTI_Mul.pas',
  UTOFYYIMPORTOBJET in '..\Lib\UTOFYYIMPORTOBJET.PAS',
  Utomaction in '..\..\Prospect\Lib\UTOMACTION.PAS',
  UTomArticle in '..\..\Gescom\Lib\UTomArticle.pas',
  UTOMBanque in '..\Lib\UTOMBANQUE.PAS',
  uTOMComm in '..\Lib\UTOMCOMM.PAS',
  UTomEtabliss in '..\Lib\UTOMETABLISS.PAS',
  UTomNomen in '..\..\Gescom\Lib\UTOMNOMEN.PAS',
  UTOMUTILISAT in '..\Lib\UTOMUTILISAT.PAS',
  uTOTComm in '..\Lib\uTOTComm.pas',
  uTreeTobFrame in '..\Lib\uTreeTobFrame.pas' {FFrameTreeTob: TFrame},
  uVoirSuiviPiece in '..\..\Gescom\Lib\uVoirSuiviPiece.pas',
  ValidateInv in '..\..\Gescom\Lib\VALIDATEINV.PAS' {ValidateForm},
  Ventana in '..\Lib\Ventana.pas' {FVentAna},
  VENTIL in '..\..\Compta\LibC\VENTIL.PAS' {FVentil},
  VentilCpta in '..\..\Gescom\Lib\VentilCpta.pas',
  VentType in '..\..\Compta\LibC\VentType.pas',
  ViergeShow in '..\..\Gescom\Lib\VIERGESHOW.PAS' {FViergeShow},
  WACTION in '..\..\Gescom\LibW\WACTION.PAS',
  wActionsTables in '..\Lib\WACTIONSTABLES.PAS',
  wCommuns in '..\Lib\WCOMMUNS.PAS',
  wFormConv in '..\..\Gescom\LibW\WFORMCONV.PAS',
  wFormConv_Tof in '..\..\Gescom\LibW\WFORMCONV_TOF.PAS',
  wFormConv_Tom in '..\..\Gescom\LibW\WFORMCONV_TOM.PAS',
  wFormConv_Tot in '..\..\Gescom\LibW\WFORMCONV_TOT.PAS',
  wFormConvMul_Tof in '..\..\Gescom\LibW\WFORMCONVMUL_TOF.PAS',
  wFormConvVar_Tot in '..\..\Gescom\LibW\WFORMCONVVAR_TOT.PAS',
  wFormConvVarDef_Tof in '..\..\Gescom\LibW\WFORMCONVVARDEF_TOF.PAS',
  wFormConvVarDef_Tom in '..\..\Gescom\LibW\WFORMCONVVARDEF_TOM.PAS',
  wJetons in '..\Lib\WJETONS.PAS',
  WJOURNALACTION in '..\..\Gescom\LibW\WJOURNALACTION.PAS',
  WJOURNALACTIONMUL_TOF in '..\..\Gescom\LibW\WJOURNALACTIONMUL_TOF.PAS',
  wMulRecherche_Tof in '..\Lib\wMulRecherche_Tof.pas',
  WPARAM in '..\Lib\WPARAM.PAS',
  WPARAMFONCTION in '..\..\Gescom\LibW\WPARAMFONCTION.PAS',
  wPrintTvDetail in '..\Lib\wPrintTvDetail.pas',
  wrapport in '..\Lib\wrapport.pas',
  WREVISION in '..\..\Gescom\LibW\WREVISION.PAS',
  WTOF in '..\..\Gescom\LibW\WTOF.PAS',
  WTOM in '..\..\Gescom\LibW\WTOM.PAS',
  wTot in '..\..\Gescom\LibW\wTot.pas',
  WUNITESMUL_TOF in '..\..\Gescom\LibW\WUNITESMUL_TOF.PAS',
  XVISingleton in '..\..\Compta\LibN\XVISingleton.pas',
  YAlertesConst in '..\Lib\YALERTESCONST.PAS',
  YPlanning in '..\Lib\YPLANNING.PAS',
  YPLANNING_TOM in '..\Lib\YPLANNING_TOM.PAS',
  YRESSOURCE in '..\Lib\YRESSOURCE.PAS',
  YRESSOURCE_TOM in '..\Lib\YRESSOURCE_TOM.PAS',
  YTABLEALERTES_TOM in '..\Lib\YTABLEALERTES_TOM.PAS',
  yTarifs in '..\..\Gescom\Lib\yTarifs.PAS',
  yTarifs_TOM in '..\..\Gescom\Lib\yTarifs_TOM.pas',
  yTarifsBascule in '..\..\Gescom\Lib\yTarifsBascule.pas',
  yTarifsBascule_TOF in '..\..\Gescom\Lib\yTarifsBascule_TOF.PAS',
  yTarifsCommun in '..\..\Gescom\Lib\YTARIFSCOMMUN.PAS',
  yTarifsEdition in '..\..\Gescom\Lib\YTARIFSEDITION.PAS',
  yTarifsEdition_TOF in '..\..\Gescom\Lib\yTarifsEdition_TOF.PAS',
  yTarifsFourchette_TOF in '..\..\Gescom\Lib\yTarifsFourchette_TOF.pas',
  yTarifsFourchette_TOM in '..\..\Gescom\Lib\YTARIFSFOURCHETTE_TOM.PAS',
  yTarifsLignes_TOF in '..\..\Gescom\Lib\yTarifsLignes_TOF.pas',
  yTarifsMUL_TOF in '..\..\Gescom\Lib\yTarifsMUL_TOF.pas',
  yTarifsParametres_TOF in '..\..\Gescom\Lib\yTarifsParametres_TOF.pas',
  yTarifsParametres_TOM in '..\..\Gescom\Lib\yTarifsParametres_TOM.pas',
  yTarifSpecial_TOF in '..\..\Gescom\Lib\yTarifSpecial_TOF.pas',
  yTarifSpecial_TOM in '..\..\Gescom\Lib\yTarifSpecial_TOM.pas',
  YYBUNDLE_TOF in '..\Lib\YYBUNDLE_TOF.PAS',
  YYYPLANNING_MUL_TOF in '..\Lib\YYYPLANNING_MUL_TOF.PAS',
  YYYRESSOURCE_MUL_TOF in '..\Lib\YYYRESSOURCE_MUL_TOF.PAS',
  ZCompte in '..\..\Compta\LibC\ZCompte.pas',
  ZCumul in '..\..\Compta\LibC\ZCumul.pas';

{$R *.RES}

begin
  Application.Initialize;
  InitAgl;
  Application.Title := 'Administration Sociétés';
  Application.CreateForm(TFMenuG, FMenuG);
  Application.CreateForm(Tgctie, gctie);
  InitApplication ;
  SplashScreen:=NIL  ;
  if paramcount=0 then
     BEGIN
     SplashScreen := TSplashScreen.Create(Nil) ;
     SplashScreen.Show ;
     SplashScreen.Update ;
     END ;
  Application.Run;
end.
