unit ValideBPdsSCM;

interface

uses UCtx;

procedure ValidationBPdansSCM(const codeSession:string);

implementation

uses uutil;

procedure ValidationBPdansSCM(const codeSession:string);
begin
 //suppression dans qtranche et qtrandetd des enr venant de la prévision
 MExecuteSql('DELETE FROM QTRANCHE WHERE '+WhereCtx(['qtranche'])+
            ' AND QT_TYPEBESOIN="2"',
            'ValideBPdsSCM (ValidationBPdansSCM).');
 MExecuteSql('DELETE FROM QTRANDETD WHERE '+WhereCtx(['qtrandetd'])+
            ' AND QTD_TRANCHE NOT IN '+
            '(SELECT QT_TRANCHE FROM QTRANCHE WHERE '+WhereCtx(['qtranche'])+')',
            'ValideBPdsSCM (ValidationBPdansSCM).');

 //insert dans qtranche et qtrandetd
 //à partir de qbpbudgetprev
 MExecuteSql('INSERT INTO QTRANCHE (QT_CTX,QT_SAISON,QT_ARTTECH,QT_TRANCHE,'+
            'QT_QTETRANCHE,QT_QTEPREVUE,QT_DATEFIN,QT_TYPEBESOIN) '+
            'SELECT "'+ValeurContexte('qtranche')+'",QBB_VALAXEBP1,QBB_VALAXEBP2,'+
            'QBB_VALAXEBP18,'+
            'SUM(QBB_QTEBPT1+QBB_QTEBPT2+QBB_QTEBPT3+QBB_QTEBPT4+QBB_QTEBPT5+'+
            'QBB_QTEBPT6+QBB_QTEBPT7+QBB_QTEBPT8+QBB_QTEBPT9+QBB_QTEBPT10+'+
            'QBB_QTEBPT11+QBB_QTEBPT12+QBB_QTEBPT13+QBB_QTEBPT14+QBB_QTEBPT15+'+
            'QBB_QTEBPT16+QBB_QTEBPT17+QBB_QTEBPT18+QBB_QTEBPT19+QBB_QTEBPT20),'+
            'SUM(QBB_QTEBPT1+QBB_QTEBPT2+QBB_QTEBPT3+QBB_QTEBPT4+QBB_QTEBPT5+'+
            'QBB_QTEBPT6+QBB_QTEBPT7+QBB_QTEBPT8+QBB_QTEBPT9+QBB_QTEBPT10+'+
            'QBB_QTEBPT11+QBB_QTEBPT12+QBB_QTEBPT13+QBB_QTEBPT14+QBB_QTEBPT15+'+
            'QBB_QTEBPT16+QBB_QTEBPT17+QBB_QTEBPT18+QBB_QTEBPT19+QBB_QTEBPT20),'+
            'QBB_DATEBP,"2" '+
            'FROM QBPBUDGETPREV WHERE QBB_CODESESSION="'+codeSession+
            '" GROUP BY QBB_VALAXEBP1,QBB_VALAXEBP2,'+
            'QBB_VALAXEBP18,'+
            'QBB_DATEBP HAVING SUM(QBB_QTEBPT1+QBB_QTEBPT2+QBB_QTEBPT3+QBB_QTEBPT4+QBB_QTEBPT5+'+
            'QBB_QTEBPT6+QBB_QTEBPT7+QBB_QTEBPT8+QBB_QTEBPT9+QBB_QTEBPT10+'+
            'QBB_QTEBPT11+QBB_QTEBPT12+QBB_QTEBPT13+QBB_QTEBPT14+QBB_QTEBPT15+'+
            'QBB_QTEBPT16+QBB_QTEBPT17+QBB_QTEBPT18+QBB_QTEBPT19+QBB_QTEBPT20)<>"0" ',
            'ValideBPdsSCM (ValidationBPdansSCM).');
 MExecuteSql('INSERT INTO QTRANDETD (QTD_CTX,QTD_SAISON,QTD_ARTTECH,QTD_TRANCHE,'+
            'QTD_NUMDETTR,QTD_COLORIS,QTD_FS,QTD_MAGASIN,'+
            'QTD_QTC1,QTD_QTP1,QTD_QTC2,QTD_QTP2,QTD_QTC3,QTD_QTP3,'+
            'QTD_QTC4,QTD_QTP4,QTD_QTC5,QTD_QTP5,QTD_QTC6,QTD_QTP6,'+
            'QTD_QTC7,QTD_QTP7,QTD_QTC8,QTD_QTP8,QTD_QTC9,QTD_QTP9,'+
            'QTD_QTC10,QTD_QTP10,'+
            'QTD_QTC11,QTD_QTP11,QTD_QTC12,QTD_QTP12,QTD_QTC13,QTD_QTP13,'+
            'QTD_QTC14,QTD_QTP14,QTD_QTC15,QTD_QTP15,QTD_QTC16,QTD_QTP16,'+
            'QTD_QTC17,QTD_QTP17,QTD_QTC18,QTD_QTP18,QTD_QTC19,QTD_QTP19,'+
            'QTD_QTC20,QTD_QTP20) '+
            'SELECT "'+ValeurContexte('qtrandetd')+'",QBB_VALAXEBP1,QBB_VALAXEBP2,QBB_VALAXEBP18,'+
            'DAY(QBB_DATEBP),QBB_VALAXEBP3,QBB_VALAXEBP4,QBB_VALAXEBP7,'+
            'SUM(QBB_QTEBPT1),SUM(QBB_QTEBPT1),SUM(QBB_QTEBPT2),SUM(QBB_QTEBPT2),'+
            'SUM(QBB_QTEBPT3),SUM(QBB_QTEBPT3),SUM(QBB_QTEBPT4),SUM(QBB_QTEBPT4),'+
            'SUM(QBB_QTEBPT5),SUM(QBB_QTEBPT5),SUM(QBB_QTEBPT6),SUM(QBB_QTEBPT6),'+
            'SUM(QBB_QTEBPT7),SUM(QBB_QTEBPT7),SUM(QBB_QTEBPT8),SUM(QBB_QTEBPT8),'+
            'SUM(QBB_QTEBPT9),SUM(QBB_QTEBPT9),SUM(QBB_QTEBPT10),SUM(QBB_QTEBPT10), '+
            'SUM(QBB_QTEBPT11),SUM(QBB_QTEBPT11),SUM(QBB_QTEBPT12),SUM(QBB_QTEBPT12),'+
            'SUM(QBB_QTEBPT13),SUM(QBB_QTEBPT13),SUM(QBB_QTEBPT14),SUM(QBB_QTEBPT14),'+
            'SUM(QBB_QTEBPT15),SUM(QBB_QTEBPT15),SUM(QBB_QTEBPT16),SUM(QBB_QTEBPT16),'+
            'SUM(QBB_QTEBPT17),SUM(QBB_QTEBPT17),SUM(QBB_QTEBPT18),SUM(QBB_QTEBPT18),'+
            'SUM(QBB_QTEBPT19),SUM(QBB_QTEBPT19),SUM(QBB_QTEBPT20),SUM(QBB_QTEBPT20) '+
            'FROM QBPBUDGETPREV WHERE QBB_CODESESSION="'+codeSession+
            '" GROUP BY QBB_VALAXEBP1,QBB_VALAXEBP2,'+
            'QBB_VALAXEBP18,'+
            'DAY(QBB_DATEBP),QBB_VALAXEBP3,QBB_VALAXEBP4,QBB_VALAXEBP7 '+
            'HAVING SUM(QBB_QTEBPT1+QBB_QTEBPT2+QBB_QTEBPT3+QBB_QTEBPT4+QBB_QTEBPT5+'+
            'QBB_QTEBPT6+QBB_QTEBPT7+QBB_QTEBPT8+QBB_QTEBPT9+QBB_QTEBPT10+'+
            'QBB_QTEBPT11+QBB_QTEBPT12+QBB_QTEBPT13+QBB_QTEBPT14+QBB_QTEBPT15+'+
            'QBB_QTEBPT16+QBB_QTEBPT17+QBB_QTEBPT18+QBB_QTEBPT19+QBB_QTEBPT20)<>"0" ',
            'ValideBPdsSCM (ValidationBPdansSCM).');

 //ATTENTION
 //pour insert de qtrandetd
 //trouver une solution pour le numdettr
 //pour le cas où il y a des coloris fs mag differents
 //il y a des cles non unique
 //solutions : numdettr sur 36 code sql increment
 //            passer par des Qtobins

 

end;

end.
