{***********UNITE*************************************************
Auteur  ...... : D.T.
Créé le ...... : 22/02/2003
Modifié le ... :   /  /
Description .. : Unité contenant tous les uses de la paie
Mots clefs ... :
*****************************************************************}
unit utestprojet;

interface

uses CLasses,
     SysUtils;

implementation
uses
{ NOM DU SOURCE DELPHI **** NOM DES FICHES ASSOCIEES }
AssistSOPaie,                              {}
ImportISIS,                                {}
CALCULACF_MUL_TOF,
CDETICKETRESTAU_TOF,
CONSULTMAINT_MUL_TOF,
CRITMAINTIEN_MUL_TOF,
CRITMAINTIEN_TOM,
MAINTIEN_TOM,
MUL_REGLTIJSS_TOF,
PGANALYSECDETCK_TOF,
PGANALYSESAL_TOF,
PGCalculACF,
PGCODISTRIBUTION_TOT,
PgDADSBilaterale,                          {}
PGDucsEdiOutils,
PgEnvoiDucsEdi,
PGEVOLUTIONEFFECTIF_TOF,
PGEVOLUTIONMASSE_TOF,
PGHierarchie,
PGIJSS,         // IJSS pour calcul bulletin
PGIJSSMaintien, // calcul du maintien pour bulletin
PGMULCDEXIST_TOF,
PGMULEXERSOCIAL_TOF,
PGMULSAITICK_TOF,
PgoutilsFormation,
PgOutilsHistorique,
PGPlanningSessionForm,
PGPREPCDETK_TOF,
PGSAITICK_TOF,
PGTICKETSTOCK_TOF,
PGTKPURGE_TOF,
REGLESMAINTIEN_TOF,
REGLTIJSS_TOF,
SUIVIIJSS_MUL_TOF,
STAREGLTIJ_TOF,
TICKETINTEGR_TOF,
TICKETRESTAURANT_TOM,
UTofPG_AideSaisPrim,
UTofPG_Anal_HistoPrimes,
UTofPG_AnalyseAnimateurs,
UTofPGAnalayseCompetences,
UTofPG_AnalyseFormation,
UTofPG_AnalysePrevisonnelForm,
UTOFPG_CONSULTPRIM,
UTofPG_DADS2_Edit,                         {DADSB_EDITION}
UTofPG_DADS2_Prep,                         {DADS2_PREP}
UTofPG_DADSHonorRecupxls,                  {DADSHON_RECUPXLS}
UTofPG_ExportGRH,
UTofPG_MulDADS2,                           {MUL_DADS2}
UTofPG_MulDADS2_Honor,                     {MUL_DADS2_HONOR}
UTOFPG_MULDADS2_TIERS,                     {MUL_DADS2TIERS}
UtofPg_MulDucsEdi,
UtofPg_MulDucsRecap,
UTofPG_MulEtabForfaitForm,
UTofPG_MulForfaitForm,
UTofPG_MulFormations,
UTofPG_MulHistoRetenue,
UTofPG_MulModifCoeff,                      {MODIFCOEFF_MUL}
UTofPG_MulModifCoeffSal,                   {MODIFCOEFFSAL_MUL}
UTOFPG_MulSalaireForm,
UTofPG_MulSessionAnimat,
UTOFPG_NETSERVICE,
UTofPG_SalarieRessource,
UTofPGCalcCongesSpec,
UTofPGCalcFractionDetail,
UTofPGCalcSalaireForm,
UTOFPGCalendrierExcel,
UTofPGCasParticulierProfil,
UTofPGCongesSpecEntre,
UTOFPGConsultService,
UtofPGCursusSaisieListe,
UTofPGCursusSalarie,
UTofPGCursusSession,
UTofPGEdit_CongesSpec,
UTofPGEdit_RetenueEcheancier,
UTofPGEdit_RetenueSal,
UTOFPGEditBilanSocial,
UTofPgEditDeclaration2483,
UTofPGEditFormationGlobal,
UTofPGEditFraisGeneraux,
UTOFPGEditForScoring,
UTofPgEditLienRubrique,
UTOFPGEdittionsCompetences,
UtofPGEditionsFormation,
UTofPGEditMMOTob,
UTofPGEditSuiviCarriere,
UTofPGEditSuiviFormationResponsable,
UTofPGEdtForm_SuiviGestion,
UTofPGEdtForm_SuiviPedagogique,
UTofPGEnvoiForm,
UTofPGFormationCarriere,
UTofPgFraisSalForm,
UTofPgHistoRetenue,
UTofPGInvestFormation,
UTofPG_MulScoring,
UTofPGMsaCalcPeriodes,
UTofPGMSAEntreprise,
UTofPGMul_calcFraction,
UTofPGMul_Cursus,
UTofPGMul_FormCursus,
UTOFPGMul_InscFor,
UTofPGMul_MSAEvolutions,
UTOFPGMul_MSAPeriodes,
UtofPgMul_PlafondForm,
PGMUL_RHCOMPET_TOF,
UTofPGMul_RetenueSal,
UTOFPGMul_SessionStage,
UTofPGMul_TypeRetenue,
UTofPgMulCongesSpec,
UTofPGMulCursusSession,
UTofPGMulDeclarations,
UTofPGMulEnvoiForm,
UTofPGMulEnvoiFormFact,
UTofPGMulEnvoiSession,
UTofPGMulExerFormation,
UTofPGMulFraisSalForm,
UTOFPGMulGestionCarriere,
UTOFPGMulSalarie_res,
UTOFPGMulStage,
UTofPgOrdreRetenue,
UTofPGPlanningFormation,
UTofPGPrep_CongesSpec,
UTofPGPrep_MSAEdi,
UTofPGPrep_EnvoiForm,
UtofPGPresenceform,
UTofPGRazFormation,
UTOFPGReaffectFormation,
UTOFPGReaffectFormationPrevisionnel,
UTofPGRecupBudgetPrevisionnel,
UTofPgRecupPrevisionnel,
UTofPGSaisieCompetSalarie,
UTofPgSaisieFormation,
UTofPGSaisieFraisSal,
UTofPgSaisieFraisSalFor,
UTofPGSaisieGestionCarriere,
UTofPGSaisieInscBudget,
UtofPGScoring,
UTofPGTrancheRemRet,
UTofPgValidInscSession,
UTofPGValidResponsFor,
UTofSaisPrim_Rem,
RHCOMPETENCES_TOM,
RHCOMPETRESSOURCE_TOM,
UTomCalcFraction,
UTomCongesSpectacles,
UTomCursus,
UTomDADS2Honoraires,                       {DADS2_HONOR}
UTomDADS2Salaries,                         {DADS2_SALARIE}
UTomDeclarations,
UtomEnvoiFormation,
UTOMEVOLUTIONSAL,                          {EVOLUTIONSAL}
UTOMExerFormation,
UTomForfaitForm,
UTOMFormations,
UTomFraisSalPlafond,
UTomFraisSessionSal,
UTomHistoRetenue,
UTOMInscrFormation,
UTOMModifCoeff,                            {MODIFCOEFF}
UTOMMotifSal,
UTOMMSAEvolutionsPE2,
UTomMSAPeriodesPE31,
UTOMPAIEBQORG,
UtomPgActivite,
UTomRetenueSalaire,
UTomSalaireForm,
UTomScoringDef,
UTOMSESSIONANIMAT,
UTOMSessionStage,
UTOMStage,
UTOMStageObjectif,
UTomTypeRetenue,
UTOTPGFormationTabletteLibre,
uTOFEtatsChaines,      // COMPTA\LIBN
        {**MASSE SALARIALE**}
UtofPGAnalyseAugm,
UTofPGAugmDetailSalarie,
UTofPGAugmentationCat,
UtofPGAugmentationGlobale,
UtofPGAugmentationIntegr,
UTofPGAugmentationSal,
UTofPGAugmentationSuivi,
UtofPGAugmGeneration,
UTofPGEditionAugmentation,
UTofPGMul_Augmentation,
UTofPGMul_AugmExclus,
UTofPGMul_AugmGenere,
UTofPGMul_AugmParam,
UTOFPGMULAUGMINTEGRATION,
UTomAugmExclus,
UTomAugmParam,
       {**GESTION DIF**}
UTofPGCompteursDIF,
UTofPGEditCompteursDIF,
UTofPGEditDemandeDIF,
UTofPGEditMvtsDIF,
UTofPGEditRecapDIF,
UtofPGMul_CompteursDIF,
UTofPGMvtsFormationPaie,
UtofPGMul_ParamFormAbs,
UTomParamFormAbs,
CONFIDENTIALITE_TOF,  // Commun\lib
HManifest,            // Commun\lib
USERGRP_TOM,          // Commun\lib
UTOMBanque,           // Commun\lib
UTomContact,          // Commun\lib
UTomEtabliss,         // Commun\lib
UtomLiensOle,         // Commun\lib
UTomMODEPAIE,         // Commun\lib
UTomModeregl,         // Commun\lib
UTomRIB,              // Commun\lib
UTOMUTILISAT,         // Commun\lib
//? CPGENERAUX_TOM,       // compta\LIB4 VG Voir si on l'utilise
//? SOUCHE_TOM,           // compta\Lib4 VG Voir si on l'utilise
UTOMAnn,              // DP\Lib
UTofHoraireStd,       // Gescom\LibA
UTOFPRINTCALREGLE,    // Gescom\LibA
//? UtofRessource_Mul,    // Gescom\LibA VG Voir si on l'utilise
UTOMCalendrierRegle,  // Gescom\LibA
UTomFerie,            // Gescom\LibA
AGLInitPaie,
EntPaie,
EuroPaiePgi,
GestionAssocie,
MenuDispPS5,                               {}
MulOrganismes_TOF, // remplace UtomOrganismePaie à retirer du projet
OlePaiePGI,
OrganismePaie_TOM, // remplace UtomOrganismePaie à retirer du projet
P5Def,
P5RecupInfos,
P5Util,
//PaieUtilCompta,
PARAMEXTPAIE_TOM,
PartEtab,
PG_DADSHONOR_TOF,                          {DADS_HONORAIRES}
PG_OutilsEnvoi,
PGANNUAIRE_TOF,
//PGAssistOLE,
PGCalendrier,
PGCommun,
PgCongespayes,
PgDADSCommun,                              {}
PGDADSControles,                           {}
PgDADSOutils,                              {}
PgDucsOutils,
PGEDIT_DADSPER_TOF,                        {EDITDADSPER;EDITFICHIERDADS}
PGEDITDADSHON_TOF,                         {EDITDADSHON}
PgEditOutils,
PGEditOutils2,
PGEdtEtat,
PGFusionWord,
PGGenerationVirement,
//PGGestionMP,
PGMULDADSHONOR_TOF,                        {MUL_DADS_HONOR}
PGOperation,
Pgoutils,
PgOutils2,
PgOutilseAgl,
PGPlanning,
PGVisuObjet,
PGVLU,
RubriqueProfil,
SaisBul,
uPaieBases,
uPaieCotisations,
uPaieCumuls,
uPaieExecpt, // Gestion des execptions
uPaieEltNatCEG,
uPaieEltNatDOS,
uPaieEltNatSTD,
uPaieEltDynSal,
uPaieEltDynEtab,
uPaieEltDynPop,
uPaieEltNiveauRequis,
uPaieEtabCompl,
uPaieMinConvPaie,
uPaieMinimumConv,
uPaieProfilsPaie,
uPaieRemunerations,
uPaieVariables,
uPaieVentiCot,
uPaieVentiRem,
UTof_CommEAgl,
UTof_mulhistoimport,
UTof_mulhistosal,
UTof_Razenrimport,
UTofBases_Bul,
UTOFCongesDetails,
UTOFCongesGRP,
UTOFCongesGrpMul,
UTOFCongesPayes,
UTOFCongesRazMul,
UTofCot_Bul,
UTofCumul_Bul,
UTOFDECLARATIONHANDI,
UTofEd_BulSal,
UTOFEDITMEDTRAV,
UTOFEDITPLANMDT,
UtofEListetables,
UTOFHANDICAPE,
UTOFIndemniteCP,
UTOFMOUVMAINOEUVRE,
UTOFmulreprisecp,
UTofPG_AcompteGrp,                         {ACOMPTE_GRP}
UTofPG_AdmineAgl,
UTofPG_AnalyseGrh,
UTOFPG_AnaSalRub,
UTOFPG_BasculeEuro,
UTOFPG_Bulcompl_mul,
UTofPG_ControlGuide,
UTofPG_DADSENTRE,                          {DADS_ENTREPRISE}
UTOFPG_DADSINACT,                          {DADS_INACTIVITE}
UTOFPG_DADSPERIODES,                       {DADSU}
UTofPG_DeCloture,
UTOFPG_DONNEURORDRE,
UTofPG_DotProvCpCompta,
UTofPG_EnvoiPrudh,
UTofPG_GeneCompta,
UTofPG_GenerAcompte,
//UTofPG_GestionMotPasse,
UTofPG_GESTIONDOS,
UTofPG_GestionStd,
UTofPG_GUIDEECRMUL,
UTofPG_IntegPrim,
UTofPG_MulAbsence,
UTofPG_MulAcompte,
UTofPG_MulAcompteGrp,                      {MUL_ACOMPTEGRP}
UTofPG_MulAffectDcro,
UTofPG_MulAnalContrat,
UTofPG_MulAssedic,                         {MUL_ATTESTASSED}
UTOFPG_MulAttestation,
UtofPG_MulClotureCP,
UTofPG_MulContrat,
UTofPG_MulDADS,                            {MUL_DADS}
UTofPG_MulDADSFichier,                     {MUL_DADS_FICHIER}
UTofPG_MulDeportSal,
UTofPG_MulDucsEnTete,
UTofPG_MulDucsInit,
UTofPG_MulDucsParam,
UTofPGMul_DUCSPurge,
UTOFPG_MulEmploiInterim,
UTofPG_MulEnvoiSocial,
UTOFPG_MulInterimaire,
UTofPG_MulObjectifStage,
UTofPG_MulPrepAuto,
UTofPG_MulRazSal,
UTofPG_MulReaffAnal,
UTofPG_MulReprise,
UTofPG_MulSaisieBul,
UTofPG_MulSaisRub,
UTofPG_MulTauxAT,
UTofPG_MulVCompta,
UTofPG_MulVentilCot,
UTofPG_Organigramme_TV,
UTOFPG_OrigineRub,
UTofPG_PaieEnvers,
UTofPG_PrepAuto,
//UTofPG_PrepBudg,
UTofPG_PrepDadsU,                          {PREP_COPAYM;PREP_DADSB;PREP_DADSU}
UTofPG_PrepPrudh,
UTOFPG_PRUDH_DEF,
UTofPG_ReaffAnalAuto,
UTofPG_ReaffCodePcs,
UTofPG_RecupXls,
UTofPG_RepCumul,
UTofPG_SaisPrim,
UTofPG_SAISRUB,
UTOFPG_SalDotCp_mul,
UTOFPGASSEDIC_spectacle,
UtofPGDucs,
UTOFPgDuplication,
UtofPGEABSENCEMUL,
UTofPgEdit_Enfants,
UTOFPGEditAccTravail,
UTOFPGEditAnalytique,
UTOFPGEditBasculEuro,
UTOFPGEditBaseCotisation,
UTOFPGEditBulletin,
UTOFPGEditBullPrepa,
UTOFPGEditCalendrier,
UTOFPGEDITCHEQUESACOMPTES,
UTOFPGEDITCHEQUESSALAIRES,
UTofPGEditComparatifDADS,
UTogPGEditContratTravail,
UTOFPGEditCumul,
UTOFPGEditDeclaration,
UTOFPGEditDue,
UTofPGEditExonerationDADS,
UTofPGEditFicheSalarie,
UTOFPGEditFicInd,
UtofPGEditInterimaires,
UTOFPGEditJournalPaie,
UTOFPGEditMaladie,
UTOFPGEditMSA_DeclSalaire,
UTOFPGEditParametre,
UTOFPGEditProvisionCp,
UTOFPGEditRecapitulatifPaie,
UTOFPGEditReduction,
UTOFPGEditReglements,
UTOFPGEditSalaries,
UTOFPGEditSolde,
UTOFPGEtatLibre,
UTOFPGEtats,
//UTOFPGEtatsChaines_Modifie,
UTOFPGExportPlanning,
UTofPGHistoGroupee,
UTofPGHistoGroupeeGen,
UTofPGHistoGroupeeXls,
UTofPGHistoGroupeeLegende,
UTOFPGFiche,
UTOFPGGenerationVirement,
UtofPgImportFic,
UTOFPGListedoc,
UTOFPGListePersonnelDuAu,
UTOFPGMul_Service,
UTOFPGMULASSEDIC_spectacle,
UtofPGMULRECAP,
UTOFPGParametreSoc,
UTOFPGPlaning,
UTOFPGReaffectSalarie,
UTOFPGReaffectTable,
//UTOFPGReaffectTable_modif,
UTOFPGSaisieSalRtf,
UTOFPGUtilitaireCP,
UTOFPGVirementAcp,
UTOFPLANMDT,
UTofRem_Bul,
UTofRepriseCP,
UTOFResponsableServices,
UTOFSalarie_anal,
UTOFSalarie_mul,
UTOFSALSANSVISITE,
UTOFValoabsence,
UTOMAbsenceSalarie,
UTOMAttestations,                          {ASSEDIC;ASSEDIC_EAGL}
UTOMContratTravail,
UTomConventionColl,
UTOMCotisation,
UtomCotisQual,
UTOMCumulPaie,
UTOMDeclarantAttest,
UTOMDeportSal,
UTOMDonneurOrdre,
UTOMDucsAffect,
UtomDucsEntete,
UtomDucsParam,
UTOMEltNationaux,
UTOMELTNATIONDOS,
UTOMELTNIVEAUREQUIS,
UTOFPGDUPLICATIONDOS,
UTOMEmetteurSocial,
UtomEmploiInterimaires,
UTOMEtabCompl,
//UTOMExerciceSocial,
utomgroupeinterne,
UTOMGUIDEECRPAIE,
UTOMHANDICAPE,
UTomHierarchie,
UTOMHistoSaisRub,
UTOMHistoSalarie,
UTOMHoraireEtab,
UtomInstitutionPaye,
UtomInterimaires,
UTOMMasqueSaisRub,
UTOMMinimumConvent,
UTOMMotifAbs,
//UTOMOrganismePaie,
UTOMPaie,
UtomParamSalarie,
UTomPGHistoDetail,
UTOMProfilPaie,
UTOMRecapSalaries,
UTOMRemuneration,
UTOMSalaries,
UTOMServices,
UTOMTauxAT,
UTOMVariablePaie,                          {VARIABLE;VARIABLE_CAL;VARIABLE_CUM;
                                            VARIABLE_TES;VARIABLE_VAL}
UTOMVentiCotPaie,
UTOMVentiORGpaie,
UTOMVentirempaie,
UTOTPGMSAACTIVITE,
UTOTPGTabletteLibre,
UTOTPGTYPEORGANISME,
{$IFNDEF FORMATION}
UTofPG_Cloture,
{$ENDIF}
VISITEMEDTRAV_TOM,
{ Bilan Social }
PBSBILANSOCIAL_TOM,
PBSINDICATEURS_TOM,
PBSINDSELECT_TOM,
UTOFPG_BSINDCALCULES,
UTOFPG_CALINDICBS,
UtofPgEditIndBilanSocial,
UTOFPG_BSINDPRES,
UTOFPG_COHERENCE,
PGEXCEPTIONS_TOM,
AssistPgExcelOle,
PgPlanningAbsPaie,
UTofPG_MulPGExcept,
PgPlanningOutils,
CalcOLEGenericPaie,
UTOFPGEXPSOLDECP,
UTOFEDITREMUNERATION,
// EPI 03/06 ajout processus
PROCESSUS_TOM,
PROCESSUSDETAIL_TOF,
PROCESSUSDET_TOM,
PROCESSUSTRT_TOF,
UTOFSUIVIEFFECTIFS,
ANOAFFECTAUX_ETAT_TOF,
{$IFNDEF CPS1} // Pas les IDR en S1
UtofPgExportEtemptation,
CALCULSALAIREMOY_TOM,
CALCULSALMOY_TOF,
CALCULSALMOYENLANC_TOF,
CALCULSIMUL_TOF,
CALCULSIMULPARAM_TOF,
CODEPOPULATION_TOM,
CODTAB_TOM,
EDIT_CONTROLEPOP_TOF,
EDIT_SIMULATIONIDR_TOF,
UTOFMETHCALCULSALMOY,
ORDREPOPUL_TOF,
ORDREPOPULATION_TOM,
DETAILPOPULATION_TOF,
AFFECTSALPOPUL_TOF,
AFFECTSALPOP_MUL_TOF,
Paie_Cjdc,            // JeDecalre
PAIE_Cjdc_lib,        // JeDeclare
PGANALYSESALMOYEN_TOF,
PGANALYSESIMUL_TOF,
PGCALCULSALAIRE,
PGCALCULSIMULATION,
POPULATION_TOF,
REGLESPOP_TOM,
RESULTSIMUL_TOF,
RESULTSIMUL_TOM,
SALAIREMOYEN_TOF,
SALAIREMOYEN_TOM,
SALARIEPOPIDR_TOF,
SALMOYENNONCAL_TOF,
SIMULATION_TOM,
TDI_GESTIONCOMPTES_JDC_TOF, // JeDeclare
UTOF_PG_MULPOPMODULES, // gestion des habilitations/populations
PGPOPULOUTILS,
UTomPGPARAMETRESASSOC,
PGHABILITATIONS_TOM,
UtofPG_MSGBOX_LISTALERTE,
{$ENDIF}
UTOFPG_EDITDADSCONT,
UTOFPG_DADSDATE,
UTofPG_MULDADSUAFFECT,
UTOMPUBLICOTIS,
UTofPGExportRTF,
UTofPGImportRTF,
UTofPGSuppRTF,
UtofPGSaisieRtDefaut,
AfterImportGEDPAIE, // Mise en place GED Salarié
PNewDocument,
UtilGedPaie,
UtofRechGedPaie,
UtofPG_Libre,
PAIETOM,
UTofPG_MulTablesDyna,
UTOMTABLEDIMENT,
PGTablesDyna,
UTofPG_TABLESDYNADUP,
PgPresence,
UTofPG_PresCloture,
UTOFPG_MulPGCumExcept,
UtofPGHistoDetailConsult,
UTofPGMulDetailHisto,
UTofPGSaisielisteHistorique,
UTofPGSaisielisteEltNatDos,
UtofPGSaisieZonesLibres,
UTofPGMulParamHisto,
UTofPGParamHistoStdDos,
UTofPGParamListeZL,
UTofPGMulSalarieZonelIbre,
UtofPGAnalayseZonesLibres,
UTofPGMulZLNiveau,
UTOF_PGCUMULGESTIONSPEC,
UTofPG_Parametres,
UTOFSAISIESYNELTNAT,
UtofPGHISTRETRO,
UtomPGRETROACTIV,
UtofPGRETROSIMULREM,
UtofPGRETROSIMULCOT,
UtofPGRETROACTIV,
UtofPGHISTRETROREM,
UtofPGHISTRETROCOT,
UTOFSYNELTNAT_MUL,
UTOFPGDUESAISIE,
UTofPGMulInitHisto,
UTOFPGDUPLIEMETTEUR,
UTOFPGMUL_EMETTEURSOCIAL,
UTOFPGModeleCycleEnt,
UTOMModeleCycleEnt,
UTOMJourneeType,
UTOMCycle,
UTOFPGDroitJourneeType,
UTofPG_PROFILPRESSALARIEGRP,
UTofPG_PROFILCOMPTPRES,
UTOMPGPROFILPRESENCE,
UtofPG_MULAFFPROFILPRES,
UTomPGPROFILPRESSALARIE,
UTOMEXCEPTCYCLE,
PGPlanningPresenceCycle,
UtofPG_PLANRYTHMETRAV,
PGPlanningTemplate,
PGPlanningPresenceSal,
UTofPG_PLANPRESSAL,
UTOFPGPRESINTEGPAIE,
UTOFPGintegprespaie,
UTOFPGHISTOCUMULS,
UTOF_PGrecalculPresence,
TOBWIEWCONTRAT_TOF,
UTOFPGEditMaladieMSA,
UTOFPGEDITHISTOSAL,
UTOFPGANALYSEHISTOSAL,
        {**BUDGET**}
{$IFDEF RHSEUL}
GraphUtil,
BPBasic,
BPCoeff,
BPCubeTmp,
BPEclatement,
BPFctArbre,
BPFctSession,
BPInitArbre,
BPInitPrev,
BPMaille,
BPPrevCmd,
BPPrevision,
BPUtil,
BPVueClient,
InitialisationPrev,
QBPARBRE_TOM,
QBPCALENDREP_TOM,
QBPLOI_TOM,
QBPSESSIONBP_TOM,
QUFCBPBUDGETPREV_TOF,
QUFGBPGRAPHHPR_TOF,
QUFGBPHPR_TOF,
QUFMBPMUL_TOF,
QUFQBPBUDGET_TOF,
QUFSBPARBREPREV_TOF,
QUFSBPBUDGETR3_TOF,
QUFSLARBRE_TOF,
QUFVBPARBREMODIF_TOF,
QUFVBPCALENDJOURM_TOF,
QUFVBPDETAILJOURM_TOF,
QUFVBPDETCALEND_TOF,
QUFVBPDUPLIQUER_TOF,
SynScriptBP,
UFormuleMulBP,
CstCommun,
UCtx,
UUtil,
uCtxTrait,
USema,
Udatamem,
UBasic,
UDate,
AccesNatifCBNconst,
Lesdatamems,
UQTobIns,
UGraph,
QUFGBPLOI_TOF,
{$ENDIF}
        {**STATUT DU DIRIGEANT**}
{$IFDEF STATDIR}
CLASSHistorisation,
DPMajPaieOutils,
DPJUROutilsDossiers,
dpJurOutilsGen,
UComOutils,
UJurOutils,
{$ENDIF}
UTOFPGEditAccTravailMSA,
UTOFMODEEDT_BUL,
UTOTPGLIBEMPLOI,
UTOFPGMulStageEmploi,
UTOMLienEmpForm,
UTOFPGSUPPRANAL,
UTOFPGANALYSEACHARGE,
UTofPG_MULEDITATTESTLOT,
PGRepertoire,
UTOTPGLIBGED,
YYdtLinks_Mul_tof,
YdataTypeLinks_Tom,
UTOFPG_PARAMDEFAUT,
UTOFPG_IMPORTASC,
UTOFPGCOMPTEURSCALC,
UTOMCompteursCalc,
UTOMCompteurPresence,
PGPlanningPresenceCompteurs,
UTOFPGTotalCompteurPres,
UTOFPGPlanCompteursPres,
UTOF_PGPARAMPRESENCEDUP,
UTOFPGExceptpressal,
UTOFPGEXCEPTPRESSALGRP,
UTOMExceptpresencesal,
UTOFPGEDITPRESENCE,
PGAnomaliesTraitement,
UTOFPGMVTGRP,
UTOFPGMULELTDYNGROUPEE,
UTOFPGELTDYNGROUPEE,
UTofPG_PRESCALCCOMPTEURS,
ULibEditionPaie,
BullOLE,
BullEnt,
BullEdCalc,
ULibPGContexte,
UTOFCONVENTION,
PgPlanningUnifie,
UTofPG_ARCHIREGLEMENTAIREPAIE,
UTofPG_AnalyseArchiReglPaie,
UTofPG_DIAGNOSTIC,
PGTreeTobFrame,
UTomCOTISCONTRAT,
UTomCONTRATPREV,
PGTobOutils,
UTOFMULTIDOSSIERS,
UTOFPG_DADSU_ETAB,
UTOFPG_MulDADSEtab,
PGFicheJob,
PGFicheJobMultiDossier,
UTofPG_DADSPrevEvt,
UTOF_PGEDITCPTCESACQUER,
PgOutilsGrids,
CPCODEPOSTAL_TOF;

////////////////////////////////////////////////////////////////////////////////
initialization
   ;

finalization
  ;


end.
