unit galDossierCste;

interface

// Codes d'erreur en création de dossier
const
  TDOSS_CREATIONOK = 0;
  TDOSS_DRIVERNOTSUPPORTED = -1;
  TDOSS_NOSHAREDDISK = -2;
  TDOSS_DISKNOTEXISTS = -3;
  TDOSS_BADCEGIDENV = -4;
  TDOSS_BADPERSON = -5;
  TDOSS_NOPERSON = -6;
  TDOSS_PERSONWITHDOSS = -7;
  TDOSS_BADNODOSSIER = -8;
  TDOSS_NODOSSREFUSED = -9;
  TDOSS_DOSSALREADYEXISTS = -10;
  TDOSS_EXISTSANDREFUSED = -11;
  TDOSS_BADDBMODELE = -12;
  TDOSS_EXISTINGDBFILE = -13;
  TDOSS_DBMODELEBUSY = -14;
  TDOSS_CANTCOPYDBMODELE = -15;
  TDOSS_CANTCOPYLOGDBMODELE = -16;
  TDOSS_CANTREATTACHDBMODELE = -17;
  TDOSS_NEWDBCONNECTFAILED = -18;
  TDOSS_CANTCREATENEWDB = -19;
  TDOSS_DBMODELEINUSE = -20;
  TDOSS_CANTCREEDOSSIER = -21;
  TDOSS_CANTCREATEDBPATH = -22;
  TDOSS_CANTDBAUTOCLOSE  = -23;
  TDOSS_ERRORWITHPLUGIN = -24;
  TDOSS_BADOPTIONS = -25;
  TDOSS_BADVERSIONBASE = -26;
  TDOSS_CANTCONNECTBASE = -27;

  TDOSS_UNKNOWNERROR = -99;

implementation

end.
