program Mobilite;
uses
  SysUtils,
  Forms,
  Hent1,
  activiteutil in '..\LIBA\activiteutil.pas',
  AdressePiece in '..\LIB\AdressePiece.pas',
  AfActivite in '..\LIBA\AfActivite.pas',
  AFCalendrier in '..\liba\AfCalendrier.pas',
  AffaireCpta in '..\LIBA\AffaireCpta.pas',
  AffaireDuplic in '..\LIBA\AffaireDuplic.pas',
  AFFAIREINT_MUL_TOF in '..\LIBBTP\AFFAIREINT_MUL_TOF.pas',
  AffaireModifPiece in '..\LIBA\AffaireModifPiece.pas',
  AffaireOle in '..\LIBA\AffaireOle.pas',
  AffaireRegroupeUtil in '..\LIBA\AffaireRegroupeUtil.pas',
  affaireutil in '..\LIBA\affaireutil.pas',
  AffEcheanceUtil in '..\LIBA\AffEcheanceUtil.pas',
  AFPlanning in '..\LIBA\AFPlanning.pas' {AF_Planning},
  AFPlanningCst in '..\liba\AFPlanningCst.pas',
  AfPrepFact in '..\LIBA\AfPrepFact.pas',
  AFTableauBord in '..\LIBA\AFTableauBord.pas',
  AfterImportGEDGRC in '..\..\PROSPECT\Lib\AfterImportGEDGRC.pas',
  AfUtilArticle in '..\LIBA\AfUtilArticle.pas',
  AGLInitAff in '..\liba\AGLInitAff.pas',
  AGLInitBtp in '..\LIBBTP\AGLInitBtp.pas',
  AGLInitCommun in '..\..\COMMUN\Lib\AglInitCommun.pas',
  AglInitDialogs in '..\LIBBTP\AglInitDialogs.pas',
  AGLInitGC in '..\LIB\AGLInitGC.pas',
  AGLInitRT in '..\..\PROSPECT\lib\AGLInitRT.pas',
  AppelMouvStkEx in '..\LIBBTP\AppelMouvStkEx.pas',
  AppelsUtil in '..\LIBBTP\AppelsUtil.pas',
  AppreciationUtil in '..\LIBA\AppreciationUtil.pas',
  Arrondi in '..\LIB\Arrondi.pas',
  ArtNonMvtes_Tof in '..\LIB\ArtNonMvtes_Tof.pas',
  ARTPHOTO_TOF in '..\LIBM\ARTPHOTO_TOF.pas',
  Assist {FAssist},
  AssistAffecteDepot in '..\LIB\AssistAffecteDepot.pas' {FAssistAffecteDepot},
  AssistAffectStock in '..\Lib\AssistAffectStock.pas' {FAssistStock},
  AssistCodeAffaire in '..\LIBA\AssistCodeAffaire.pas',
  ASSISTCODEAPPEL in '..\LIBBTP\ASSISTCODEAPPEL.PAS' {FAssistCodeAppel},
  AssistContreMVtoA in '..\LIB\AssistContreMVtoA.pas' {FCmdeContreM},
  AssistCreationAffaire in '..\LIBA\AssistCreationAffaire.pas' {FAssistCreationAffaire},
  AssistCreationTarifArt in '..\LIB\AssistCreationTarifArt.pas',
  AssistDupTarif in '..\LIB\AssistDupTarif.pas',
  AssistGenereCAB in '..\LIBM\AssistGenereCAB.pas',
  AssistMajCompteurSouche in '..\LIB\AssistMajCompteurSouche.pas' {FAssistMajCptSouche},
  AssistMajTarif in '..\LIB\AssistMajTarif.pas',
  AssistMajTarifArt in '..\LIB\AssistMajTarifArt.pas',
  AssistPieceEpure in '..\LIB\AssistPieceEpure.pas' {FAssistantPieceEpure},
  AssistRazActivite in '..\LIB\AssistRazActivite.pas' {FAssistRazActivite},
  AssistStockAjust in '..\LIB\AssistStockAjust.pas' {FStockAjust},
  AssistSuggestion in '..\LIB\AssistSuggestion.pas' {FSuggestion},
  AssistUtil in '..\lib\AssistUtil.pas',
  AssistValidInv in '..\LIB\AssistValidInv.pas' {FAssistValidInv},
  BanqueCp in '..\..\COMPTA\LIB4\BanqueCp.pas' {FbanqueCP},
  BTAssistDecisionAch in '..\LIBBTP\BTAssistDecisionAch.pas' {FassistDecisionAch},
  BTComparatif_TOF in '..\LIBBTP\BTComparatif_TOF.PAS',
  BTConsos_TOF in '..\LIBBTP\BTConsos_TOF.PAS',
  BTFactImprTOB in '..\LIBBTP\BTFactImprTOB.pas',
  BTFACTTEXTES in '..\LIBBTP\BTFACTTEXTES.pas',
  BTGENCONTRETU_TOF in '..\LIBBTP\BTGENCONTRETU_TOF.pas',
  BTJoucon_TOF in '..\LIBBTP\BTJoucon_TOF.PAS',
  BTPLANNIFCH_TOF in '..\LIBBTP\BTPLANNIFCH_TOF.pas',
  BTPLANNING in '..\LIBBTP\BTPLANNING.PAS' {MonPlanning},
  BTPrepaLivr in '..\LIBBTP\BTPrepaLivr.pas',
  BTPUtil in '..\LIBBTP\BTPUtil.pas',
  BTReglDemAcomptes in '..\LIBBTP\BTReglDemAcomptes.pas',
  BTRepartition_tof in '..\LIBBTP\BTRepartition_tof.pas',
  BTREPARTTVA_TOF in '..\LIBBTP\BTREPARTTVA_TOF.pas',
  BTSaisieDate in '..\LIBBTP\BTSaisieDate.pas' {FSaisieDate},
  BTSelectDate in '..\LIBBTP\BTSelectDate.pas' {FselectDate},
  BTSELLIGBORD_TOF in '..\LIBBTP\BTSELLIGBORD_TOF.pas',
  BTTableauBord_TOF in '..\LIBBTP\BTTableauBord_TOF.PAS',
  BTTRARTHIER_TOF in '..\LIBBTP\BTTRARTHIER_TOF.pas',
  BTUtilDecisionAch in '..\LIBBTP\BTUtilDecisionAch.pas',
  BTVALIDCTRETUDE_TOF in '..\LIBBTP\BTVALIDCTRETUDE_TOF.pas',
  BTVARDOC_TOF in '..\LIBBTP\BTVARDOC_TOF.pas',
  CalcMulProspect in '..\..\PROSPECT\Lib\CalcMulProspect.pas',
  CalcOLEAffaire in '..\LIBA\CalcOLEAffaire.pas',
  CalcOLEBTP in '..\LIBBTP\CalcOLEBTP.pas',
  CalcOLEGenericBTP in '..\LIBBTP\CalcOLEGenericBTP.pas',
  CalcOLEGescom in '..\LIB\CalcOLEGescom.pas',
  CalcOleGRC in '..\..\PROSPECT\Lib\CalcOleGRC.pas',
  CalculSuggestion in '..\LIB\CalculSuggestion.pas',
  Calendres in '..\LIBA\Calendres.pas',
  CasEmplois in '..\LIB\CasEmplois.pas',
  CCACONTROLSLib_TLB in '..\..\PROSPECT\Lib\CCACONTROLSLib_TLB.pas',
  Chancel in '..\..\COMPTA\LIB4\Chancel.pas' {FChancel},
  ChangeVersions in '..\LIBBTP\ChangeVersions.pas' {FMajVerBtp},
  ChoixDupNomen in '..\LIB\ChoixDupNomen.pas',
  CLgCpte in '..\..\COMPTA\LibC\CLgCpte.pas',
  CodeSect in '..\..\COMPTA\LIBC\CodeSect.pas' {FCodesect},
  COMMERCIAL_MUL_TOF in '..\LIB\COMMERCIAL_MUL_TOF.pas',
  ConfidentAffaire in '..\liba\ConfidentAffaire.pas',
  Confidentialite_TOF in '..\..\COMMUN\Lib\Confidentialite_TOF.pas',
  CONSOLIDATION_TOF in '..\LIBM\CONSOLIDATION_TOF.PAS',
  CopierCollerUtil in '..\LIB\CopierCollerUtil.pas',
  CPSECTION_TOM in '..\..\COMPTA\Lib4\CPSECTION_TOM.PAS',
  CptaDiff in '..\LIB\CptaDiff.pas',
  CPTESAV in '..\..\COMPTA\LibC\cptesav.pas',
  CreePieceOle in '..\LIB\CreePieceOle.pas',
  Ctigrc in '..\..\PROSPECT\Lib\CtiGrc.pas',
  DECISIONACH_MUL_TOF in '..\LIBBTP\DECISIONACH_MUL_TOF.pas',
  DECISIONACH_VAL_TOF in '..\LIBBTP\DECISIONACH_VAL_TOF.pas',
  DECISIONACHAT_TOF in '..\LIBBTP\DECISIONACHAT_TOF.pas',
  DecisionAchatUtil in '..\LIBBTP\DecisionAchatUtil.pas',
  DECISIONACHNART_TOF in '..\LIBBTP\DECISIONACHNART_TOF.pas',
  DepotUtil in '..\LIB\DepotUtil.pas',
  DetailInv in '..\LIB\DetailInv.pas' {FDetailInv},
  Devise in '..\..\COMPTA\LIB4\Devise.pas' {FDevise},
  DicoBTP in '..\LIBBTP\DicoBTP.pas',
  Dimension in '..\LIB\Dimension.pas',
  DimUtil in '..\LIB\DimUtil.pas',
  Dispo_Serie_TOF in '..\LIB\Dispo_Serie_TOF.PAS',
  DpJurOutils in '..\..\DP\LIB\DpJurOutils.pas',
  DpJurOutilsEve in '..\..\DP\LIB\DpJurOutilsEve.pas',
  dpTOFCEtebac in '..\..\DP\LIB\dpTOFCEtebac.pas',
  DpUtil in '..\LIBA\DpUtil.pas',
  EBizUtil in '..\LIBEC\EBizUtil.pas',
  Echeance in '..\..\COMPTA\LIBC\Echeance.PAS' {FEcheance},
  EclateTra in '..\Lib\EclateTra.pas',
  ECRPIECE_TOF in '..\..\COMMUN\lib\ECRPIECE_TOF.pas',
  edtQR {EditQR},
  Ent1 in '..\..\COMPTA\LIB4\Ent1.pas',
  EntDP in '..\..\COMMUN\Lib\EntDP.pas',
  EntGC in '..\..\COMMUN\LIB\EntGC.pas',
  EntPGI in '..\..\COMMUN\LIB\EntPGI.pas',
  EntRT in '..\..\PROSPECT\Lib\EntRT.pas',
  EtbMce in '..\..\COMPTA\LIBL\EtbMce.pas' {FMce},
  EtbUser in '..\..\COMPTA\LIBL\EtbUser.pas' {FEtbUser},
  EtudePiece in '..\LIBBTP\EtudePiece.pas',
  Etudes in '..\LIBBTP\Etudes.pas',
  EtudesExt in '..\LIBBTP\EtudesExt.pas',
  EtudesStruct in '..\LIBBTP\EtudesStruct.pas',
  EtudesUtil in '..\libbtp\EtudesUtil.pas',
  factAcompte in '..\LIBBTP\factAcompte.pas',
  FactActivite in '..\LIBA\FactActivite.pas',
  FactAdresse in '..\LIB\FactAdresse.pas',
  FactAdresseBTP in '..\LIBBTP\FactAdresseBTP.pas',
  FactAffaire in '..\LIBA\FactAffaire.pas',
  FactArticle in '..\LIB\FactArticle.pas',
  FactBordereau in '..\LIBBTP\FactBordereau.pas',
  FactBordereauMenu in '..\LIBBTP\FactBordereauMenu.pas',
  factcalc in '..\LIB\factcalc.pas',
  FactCodeBarre in '..\LIBM\FactCodeBarre.pas',
  FactComm in '..\LIB\FactComm.pas',
  FactCommBTP in '..\libbtp\FactCommBTP.pas',
  FactContreM in '..\LIB\FactContreM.pas',
  FactCpta in '..\LIB\FactCpta.pas',
  FactCptaMode in '..\LIBM\FactCptaMode.pas',
  FactEmplacementLivr in '..\LIBBTP\FactEmplacementLivr.pas',
  FactFormule in '..\LIB\FactFormule.pas',
  FactGestParag in '..\LIBBTP\FactGestParag.pas',
  FactGrp in '..\LIB\FactGrp.pas',
  factgrpBtp in '..\LIBBTP\factgrpBtp.pas',
  FactGrpMan in '..\LIB\FactGrpMan.pas',
  FactLivrFromRecep in '..\LIBBTP\FactLivrFromRecep.pas',
  FactLotSerie in '..\LIB\FactLotSerie.pas',
  FactMinute in '..\LIBBTP\FactMinute.pas',
  FactNomen in '..\LIB\FactNomen.pas',
  FactOuvrage in '..\LIBBTP\FactOuvrage.pas',
  FactPiece in '..\LIB\FactPiece.pas',
  FactRg in '..\LIB\FactRg.pas',
  Factrgpbesoin in '..\LIBBTP\Factrgpbesoin.pas',
  FactSpec in '..\LIB\FactSpec.pas',
  FactTarifs in '..\LIB\FactTarifs.pas',
  FactTiers in '..\LIB\FactTiers.pas',
  FactTOB in '..\LIB\FactTOB.pas',
  FactTOBbtp in '..\LIBBTP\FactTOBbtp.pas',
  FactTvaMilliem in '..\LIBBTP\FactTvaMilliem.pas',
  Facture in '..\LIB\Facture.pas',
  FactureBtp in '..\LIBBTP\FactureBtp.pas',
  FactUtil in '..\LIB\FactUtil.pas',
  FactUtilBTP in '..\LIBBTP\FactUtilBTP.pas',
  FactVariante in '..\LIB\FactVariante.pas',
  FGestAffDet in '..\LIB\FGestAffDet.pas',
  FichComm in '..\..\COMMUN\LIB\FichComm.pas',
  Fiche {FFiche},
  FichGrid {FFicheGrid},
  FichList {FFicheListe},
  FPrixMarche in '..\LIB\FPrixMarche.pas',
  galDossierCste in '..\..\DP\Lib\galDossierCste.pas',
  galEnv in '..\..\DP\Lib\galEnv.pas',
  galOutil in '..\..\DP\LIB\galOutil.pas',
  GcArticle_Tof in '..\LIB\GcArticle_Tof.pas',
  GcComplPrix_tof in '..\LIB\GcComplPrix_tof.pas',
  GCControleFacture_Tof in '..\LIB\GCControleFacture_Tof.pas',
  GcFonctionVar_Tof in '..\LIB\GcFonctionVar_Tof.pas',
  GCFOURN_MUL_TOF in '..\LIB\GCFOURN_MUL_TOF.PAS',
  GCInfoFichier in '..\LIBCO\GCInfoFichier.pas' {FicheInfoTox},
  GCModifZS in '..\LIB\GCModifZS.pas',
  GCMZSUtil in '..\LIB\GCMZSUtil.pas',
  GENEREACTIONS in '..\..\PROSPECT\Lib\GENEREACTIONS.pas',
  GerePiece in '..\LIB\GerePiece.pas',
  GereTobInterne in '..\LIBA\GereTobInterne.pas',
  GestRemplArticle in '..\LIBBTP\GestRemplArticle.pas',
  GraphUtil in '..\LIB\GraphUtil.pas',
  GRS1 {FGRS1},
  HCompte in '..\..\COMPTA\LIB4\HCompte.pas' {FZoom},
  HeureUtil in '..\liba\HeureUtil.pas',
  HistorisePiece_Tof in '..\LIB\HistorisePiece_Tof.pas',
  HManifest in '..\..\COMMUN\Lib\HManifest.pas',
  HRegCpte in '..\..\COMPTA\Lib4\HREGCPTE.PAS',
  HZoomSP in '..\..\COMPTA\LIB4\HZoomSP.pas' {FZoomSP},
  ImportInnovpro in '..\LIBBTP\ImportInnovpro.pas',
  ImSaiCoef in '..\..\COMPTA\LIBI\ImSaiCoef.pas' {SaiCoefIm},
  InitSoc in '..\..\COMPTA\LIBC\InitSoc.pas' {FInitSoc},
  InvUtil in '..\LIB\InvUtil.pas',
  LanceRea_Mul_Tof in '..\LIB\LanceRea_Mul_Tof.pas',
  letbatch in '..\..\COMPTA\LIBC\letbatch.pas',
  Lettauto in '..\..\COMMUN\lib\Lettauto.pas',
  LettUtil in '..\..\COMPTA\LIBC\LettUtil.pas',
  LGCOMPTE_TOF in '..\..\COMPTA\LibN\LGCOMPTE_TOF.PAS',
  LibPlanning in '..\..\COMMUN\Lib\LibPlanning.pas',
  LigDispolot in '..\LIB\LigDispolot.pas',
  LigNomen in '..\LIB\LigNomen.pas',
  ListeDeSaisie in '..\LIB\ListeDeSaisie.pas',
  ListUsersAutorises in '..\..\commun\Lib\ListUsersAutorises.pas',
  MenuOLG {FMenuG},
  MessagesErreur in '..\Lib\MessagesErreur.pas',
  ModifTableLigOuv in '..\LIBBTP\ModifTableLigOuv.pas',
  MouvStkExContr_TOF in '..\LIB\MouvStkExContr_TOF.pas',
  MsgUtil in '..\LIBBTP\MsgUtil.pas',
  Mul {FMul},
  MULAFFECH_TOF in '..\LIBBTP\MULAFFECH_TOF.pas',
  NewCalendar in '..\libbtp\NewCalendar.pas',
  NomenAPlat in '..\LIB\NomenAPlat.pas',
  NomenErr in '..\LIB\NomenErr.pas',
  NomenLig in '..\LIB\NomenLig.pas',
  NomenUtil in '..\LIB\NomenUtil.pas',
  NouveauLot in '..\LIB\NouveauLot.pas' {FNouveauLot},
  OpenSaveDlg in '..\LIB\OpenSaveDlg.pas' {OpenSaveDialog},
  OptimizeOuv in '..\LIBBTP\OptimizeOuv.pas',
  PARAMCATTAXE_TOF in '..\LIBBTP\PARAMCATTAXE_TOF.pas',
  ParamConfid_Tof in '..\LIB\ParamConfid_Tof.PAS',
  ParamOblig_Tof in '..\LIB\ParamOblig_Tof.PAS',
  ParPieceGrp in '..\LIB\ParPieceGrp.pas',
  PgOutils2 in '..\..\Paie\lib\PgOutils2.pas',
  PIECECOURSART_TOF in '..\LIB\PIECECOURSART_TOF.PAS',
  PieceEpure_Tof in '..\LIB\PieceEpure_Tof.pas',
  PlanUtil in '..\LIBBTP\PlanUtil.pas',
  PwdDossier in '..\..\DP\LIB\PwdDossier.pas' {FPwdDossier},
  QRS1 {FQRS1},
  Rapport in '..\LIBBTP\Rapport.pas' {fRapport},
  RapSuppr in '..\..\COMPTA\LIBC\RapSuppr.pas' {FRapsuppr},
  RECONDUCTION_TOF in '..\LIBBTP\RECONDUCTION_TOF.pas',
  RecupNeg in '..\LIB\RecupNeg.pas',
  RecupNegSQL7 in '..\lib\RecupNegSQL7.pas',
  RecupSuspect in '..\..\PROSPECT\Lib\RecupSuspect.pas' {FRecupSuspect},
  RecupTarifFour in '..\LIB\RecupTarifFour.pas' {FRecupTarifFour},
  RecupTempoAssist in '..\LIBA\RecupTempoAssist.pas',
  RecupTempoParam in '..\LIBA\RecupTempoParam.pas',
  RecupTempoParamCli in '..\liba\RecupTempoParamCli.pas',
  RecupTempoParamEntite in '..\LIBA\RecupTempoParamEntite.pas',
  RecupTempoParamFjur in '..\liba\RecupTempoParamFjur.pas',
  RegenereConso_TOF in '..\LIBBTP\RegenereConso_TOF.pas',
  RegGRCPGI in '..\..\PROSPECT\LIB\RegGRCPGI.pas',
  RegTVA in '..\..\COMPTA\LIBC\RegTVA.pas',
  ResulSuggestion in '..\LIB\ResulSuggestion.pas' {FResulSuggestion},
  RTDialog in '..\..\PROSPECT\LIB\RTDialog.pas' {RT_Dialog},
  RTMenuGRC in '..\..\PROSPECT\LIB\RTMenuGRC.pas',
  RTNewDocument in '..\..\PROSPECT\LIB\RTNewDocument.pas' {FRTNewDocument},
  RTPLANNING in '..\..\PROSPECT\LIB\RTPLANNING.pas' {RT_Planning},
  RTRappel_Actions in '..\..\PROSPECT\Lib\RTRappel_Actions.pas',
  SaisComm in '..\..\COMPTA\LIBC\SaisComm.pas',
  SaisieCondition in '..\LIB\SaisieCondition.pas',
  SaisieConsommations in '..\LIBBTP\SaisieConsommations.pas',
  SaisieCorrespGPAO in '..\LIBCO\SaisieCorrespGPAO.pas' {FCorrespGPAO},
  SaisieFormule in '..\LIB\SaisieFormule.pas',
  SaisieInv in '..\LIB\SaisieInv.pas' {FSaisieInv},
  SaisieSerie_TOF in '..\LIB\SaisieSerie_TOF.pas',
  SaisieTexte in '..\LIB\SaisieTexte.pas',
  SaisieTexteValeur in '..\LIB\SaisieTexteValeur.pas' {FSaisieTexteValeur},
  SAISUTIL in '..\..\COMPTA\LIB4\SAISUTIL.pas',
  SelectDocSuggestion in '..\LIB\SelectDocSuggestion.pas',
  SelectPhase in '..\LIBBTP\SelectPhase.pas',
  SimulRentabDoc in '..\LIBBTP\SimulRentabDoc.pas',
  SimulRentabUtil in '..\LIBBTP\SimulRentabUtil.pas',
  SoldeCpt in '..\..\compta\LibC\SOLDECPT.PAS',
  SOUCHE_TOM in '..\..\COMPTA\LIB4\SOUCHE_TOM.PAS',
  Splash in '..\LIBBTP\Splash.pas',
  SplashG {SplashScreen},
  Stat in '..\lib\Stat.pas',
  StockUtil in '..\LIB\StockUtil.pas',
  Structur in '..\..\COMPTA\LIBC\Structur.pas' {FStructure},
  SyntheseUtil in '..\LIBA\SyntheseUtil.pas',
  Tablette {FTablette},
  TarifArticle in '..\LIB\TarifArticle.pas',
  TarifAutoFour in '..\LIB\TarifAutoFour.pas',
  TarifCatArt in '..\LIB\TarifCatArt.pas',
  TarifCliArt in '..\LIB\TarifCliArt.pas',
  TarifCond in '..\LIB\TarifCond.pas',
  TarifRapide in '..\LIB\TarifRapide.pas',
  Tarifs in '..\LIB\Tarifs.PAS',
  TarifTiers in '..\LIB\TarifTiers.pas',
  TarifUtil in '..\LIB\TarifUtil.pas',
  TiersPayeur in '..\..\COMPTA\LibC\TiersPayeur.pas',
  TiersUtil in '..\..\COMMUN\LIB\TiersUtil.pas',
  TofParfouDuplic in '..\LIB\TofParfouDuplic.pas',
  TomProfilUser in '..\..\COMPTA\LibN\TomProfilUser.pas',
  tradarticle in '..\LIB\tradarticle.pas',
  TraducAffaire in '..\LIBA\TraducAffaire.pas',
  TrtRecupSuspect in '..\..\PROSPECT\LIB\TrtRecupSuspect.pas' {FTrtRecupSuspect},
  TVA in '..\..\COMPTA\LIB4\TVA.pas' {FTva},
  TVAEtab in '..\..\COMPTA\LIB4\TVAEtab.pas' {FTvaEtab},
  UAFO_Calendrier in '..\LIBA\UAFO_Calendrier.pas',
  UAFO_FACTREGUL in '..\LIBA\UAFO_FACTREGUL.pas',
  UAFO_Ferie in '..\LIBA\UAFO_Ferie.pas',
  UAFO_REGLES in '..\liba\UAFO_REGLES.pas',
  UAFO_Ressource in '..\LIBA\UAFO_Ressource.pas',
  UAFO_REVPRIXCALCULCOEF in '..\LIBA\UAFO_REVPRIXCALCULCOEF.pas',
  UAFO_REVPRIXLECTURECOEF in '..\LIBA\UAFO_REVPRIXLECTURECOEF.pas',
  uBtpEtatPlanning in '..\LibBTP\uBtpEtatPlanning.pas',
  UCoherence in '..\..\DP\LIB\UCoherence.pas',
  UDimArticle in '..\LIB\UDimArticle.pas',
  UDossierSelect in '..\..\DP\LIB\UDossierSelect.pas',
  UGenereAffaire in '..\LIBBTP\UGenereAffaire.pas',
  ULibAnalytique in '..\..\COMPTA\LibC\ULibAnalytique.pas',
  ULibEcriture in '..\..\COMPTA\LIBC\ULibEcriture.pas',
  ULibExercice in '..\..\COMPTA\LibC\ULibExercice.pas',
  uLibStdCpta in '..\..\COMPTA\LIBS\uLibStdCpta.pas',
  ULibWindows in '..\..\COMPTA\LIBC\ULibWindows.pas',
  UMetreArticle in '..\LIBBTP\UMetreArticle.pas',
  UPlannifchUtil in '..\LIBBTP\UPlannifchUtil.pas',
  uRecupSQLModele in '..\..\COMMUN\lib\uRecupSQLModele.pas',
  UserGrp_tom in '..\..\COMMUN\LIB\UserGrp_tom.pas',
  UtilAction in '..\..\PROSPECT\LIB\UtilAction.pas',
  UtilAlertes in '..\..\COMMUN\LIB\UtilAlertes.pas',
  UtilArticle in '..\LIB\UtilArticle.pas',
  UtilCB in '..\..\COMMUN\Lib\utilCB.pas',
  UtilChainage in '..\..\PROSPECT\LIB\UtilChainage.pas',
  UtilConfid in '..\LIB\UtilConfid.pas',
  UtilConso in '..\LIBBTP\UtilConso.pas',
  UtilCti in '..\CTI\UtilCti.pas',
  UTILCUTOFF in '..\LIBA\UTILCUTOFF.pas',
  UtilDimArticle in '..\LIB\UtilDimArticle.pas',
  UtilDispGC in '..\LIB\UtilDispGC.pas',
  UtilDossier in '..\..\DP\LIB\UtilDossier.pas',
  UtilDuplicBordereaux in '..\LIBBTP\UtilDuplicBordereaux.pas',
  UtilEvent in '..\LIBBTP\UtilEvent.pas',
  UtilFichiers in '..\LIBBTP\UtilFichiers.pas',
  UtilFO in '..\LIB\UtilFO.pas',
  UTilFonctionCalcul in '..\LIB\UTilFonctionCalcul.pas',
  UtilGA in '..\LIBA\UtilGA.pas',
  UtilGC in '..\LIB\UtilGC.pas',
  UtilGed in '..\..\DP\LIB\UtilGed.pas',
  UtilGedRT in '..\..\PROSPECT\LIB\UtilGedRT.pas',
  UtilGenContreEtude in '..\LIBBTP\UtilGenContreEtude.pas',
  UtilGrp in '..\LIB\UtilGrp.pas',
  UtilGrpBtp in '..\LIBBTP\UtilGrpBtp.pas',
  UtilInterCompta in '..\LIB\UtilInterCompta.pas',
  UtilMenuAff in '..\liba\UtilMenuAff.pas',
  UtilMessages in '..\..\DP\LIB\UtilMessages.pas',
  UtilMetres in '..\LIBBTP\UtilMetres.pas',
  UtilMulTraitmt in '..\..\DP\Lib\UtilMulTraitmt.pas',
  UtilMulTrt in '..\LIBA\UtilMulTrt.pas',
  UtilOle in '..\..\COMMUN\Lib\UtilOle.pas',
  UtilOperation in '..\..\prospect\Lib\UtilOperation.pas',
  UtilPaieAffaire in '..\LIBA\UtilPaieAffaire.pas',
  UtilPerspective in '..\..\PROSPECT\Lib\UtilPerspective.pas',
  utilPGI in '..\..\COMMUN\LIB\utilPGI.pas',
  UtilPhases in '..\LIBBTP\UtilPhases.pas',
  UtilPlannifchantier in '..\LIBBTP\UtilPlannifchantier.pas',
  UtilPlanning in '..\LIBA\UtilPlanning.pas',
  UtilPrepFact in '..\LIBA\UtilPrepFact.pas',
  UtilRCC in '..\..\PROSPECT\Lib\UtilRCC.pas',
  UtilReglementAffaire in '..\LIBBTP\UtilReglementAffaire.pas',
  UtilRessource in '..\liba\UtilRessource.pas',
  UtilRevFormule in '..\LIBA\UtilRevFormule.pas',
  UtilRevision in '..\LIBA\UtilRevision.pas',
  UTILRT in '..\..\PROSPECT\LIB\UTILRT.PAS',
  UtilSais in '..\..\COMPTA\Lib4\UtilSais.pas',
  UtilSaisieConso in '..\LIBBTP\UtilSaisieConso.pas',
  UTilSelection in '..\..\PROSPECT\Lib\UtilSelection.pas',
  UtilSoc in '..\..\COMMUN\LIB\UtilSoc.pas',
  UtilSuggestion in '..\LIBBTP\UtilSuggestion.pas',
  UtilSuprAuxi in '..\..\COMPTA\LibC\UtilSuprAuxi.pas',
  UtilSuprTiers in '..\..\commun\Lib\UtilSuprTiers.pas',
  UtilTableauBord in '..\LIBBTP\UtilTableauBord.pas',
  UtilTaches in '..\liba\UtilTaches.pas',
  UtilTarif in '..\LIB\UtilTarif.pas',
  UtilTelCTI in '..\CTI\UtilTelCTI.pas',
  UTILULST_TOF in '..\LIB\UTILULST_TOF.PAS',
  UtilUtilitaires in '..\LIB\UtilUtilitaires.pas',
  UtilValidReapDecis in '..\LIBBTP\UtilValidReapDecis.pas',
  UtilVariables in '..\libbtp\UtilVariables.pas',
  utilxlsBTP in '..\LIBBTP\utilxlsBTP.pas',
  UTOF_BTREACPRDOC in '..\LIBBTP\UTOF_BTREACPRDOC.pas',
  UTOF_BTRECHCONTACT in '..\LIBBTP\UTOF_BTRECHCONTACT.pas',
  UTOF_BTSAISDOCEXT in '..\LIBBTP\UTOF_BTSAISDOCEXT.pas',
  Utof_RTSelectRessources in '..\..\PROSPECT\Lib\Utof_RTSelectRessources.pas',
  UTOF_VideInside in '..\LIBBTP\UTOF_VideInside.pas',
  UTofActions in '..\..\PROSPECT\LIB\UTofActions.pas',
  UtofActions_TV in '..\..\PROSPECT\LIB\UtofActions_TV.pas',
  utofafactivite_suivi in '..\LIBA\utofafactivite_suivi.pas',
  UTofAfActiviteCube in '..\LIBA\UTofAfActiviteCube.pas',
  UTOFAFACTIVITEGLOECLA in '..\LIBA\UTOFAFACTIVITEGLOECLA.PAS',
  UTofAfActiviteMul in '..\LIBA\UTofAfActiviteMul.pas',
  UTofAfActivitePai_Mul in '..\LIBA\UTofAfActivitePai_Mul.pas',
  UTofAFArticle_Mul in '..\LIBA\UTofAFArticle_Mul.pas',
  UTOFAFAUGMEN in '..\LIBA\UTOFAFAUGMEN.PAS',
  UTofAfAvenant in '..\LIBA\UTofAfAvenant.pas',
  UTofAfBaseCodeAffaire in '..\LIBA\UTofAfBaseCodeAffaire.pas',
  UTofAfBaseLigne_Mul in '..\LIBA\UTofAfBaseLigne_Mul.pas',
  UTOFAFBASEMODELEEDIT in '..\LIBA\UTOFAFBASEMODELEEDIT.pas',
  UTofAfBasePiece_Mul in '..\LIBA\UTofAfBasePiece_Mul.pas',
  UTOFAFCHOIXDATESREVAL in '..\LIBA\UTOFAFCHOIXDATESREVAL.PAS',
  UTofAfChoixEcheAffair in '..\LIBA\UTofAfChoixEcheAffair.pas',
  UTOFAFCHOIXEDITAFFAIR in '..\LIBA\UTOFAFCHOIXEDITAFFAIR.PAS',
  UtofAFEACTCHOIXINTEGR in '..\LIBA\UtofAFEACTCHOIXINTEGR.PAS',
  UTOFAFEACTIVITE_MUL in '..\LIBA\UTOFAFEACTIVITE_MUL.PAS',
  UTOFAFEACTIVITEMODIF in '..\LIBA\UTOFAFEACTIVITEMODIF.PAS',
  UTofAfFactDecideur in '..\LIBA\UTofAfFactDecideur.pas',
  UTofAffaire_Mul in '..\LIBA\UTofAffaire_Mul.pas',
  UTofAffaire_Mul_Comp in '..\LIBA\UTofAffaire_Mul_Comp.pas',
  UTofAffaire_REg in '..\LIBA\UTofAffaire_REg.pas',
  UTofAffectation in '..\LIBBTP\UTofAffectation.pas',
  UtofAffectStock in '..\LIB\UtofAffectStock.pas',
  UtofAFFormule in '..\LIBA\UtofAFFormule.PAS',
  uTofAFIndiceMul in '..\LIBA\uTofAFIndiceMul.PAS',
  UTofAfJournalAct in '..\LIBA\UTofAfJournalAct.pas',
  UtofAFMODIFCUTOFF in '..\LIBA\UtofAFMODIFCUTOFF.PAS',
  UtofAFMODIFCUTOFF_MUL in '..\LIBA\UtofAFMODIFCUTOFF_MUL.PAS',
  UtofAFMODIFCUTOFFADD in '..\LIBA\UtofAFMODIFCUTOFFADD.PAS',
  uTofAFormuleVar in '..\LIBA\uTofAFormuleVar.PAS',
  uTofAFormuleVar_Mul in '..\LIBA\uTofAFormuleVar_Mul.PAS',
  UTofAfPiece in '..\LIBA\UTofAfPiece.pas',
  UTofAfPiece_Mul in '..\LIBA\UTofAfPiece_Mul.pas',
  UTofAfPiecePro_Mul in '..\LIBA\UTofAfPiecePro_Mul.pas',
  UTofAfPieceProAnu_Mul in '..\LIBA\UTofAfPieceProAnu_Mul.pas',
  UTofAFPlanning_Mul in '..\LIBA\UTofAFPlanning_Mul.pas',
  UTofAfPrepFact in '..\LIBA\UTofAfPrepFact.pas',
  UTofAfProfilGener in '..\LIBA\UTofAfProfilGener.pas',
  uTofAfPublicationMul in '..\LIBA\uTofAfPublicationMul.pas',
  UtofAfRegroupeAffaire in '..\LIBA\UtofAfRegroupeAffaire.PAS',
  UTofAFRes_SyncWhat in '..\LIBA\UTofAFRes_SyncWhat.pas',
  UtofAFRESSOU_SYNCHRO in '..\LIBA\UtofAFRESSOU_SYNCHRO.PAS',
  UTOFAFREVCALCCOEF in '..\LIBA\UTOFAFREVCALCCOEF.PAS',
  utofAfRevEtatFacture in '..\LIBA\utofAfRevEtatFacture.pas',
  utofAfRevExportIndice in '..\LIBA\utofAfRevExportIndice.pas',
  uTofAfRevFormule in '..\LIBA\uTofAfRevFormule.PAS',
  uTofAfRevFormule_Mul in '..\LIBA\uTofAfRevFormule_Mul.pas',
  uTofAfRevFormuleEdit in '..\LIBA\uTofAfRevFormuleEdit.pas',
  utofafRevImportIndice in '..\LIBA\utofafRevImportIndice.pas',
  utofafrevision in '..\LIBA\utofafrevision.pas',
  utofAfRevisionIndice in '..\LIBA\utofAfRevisionIndice.pas',
  uTofAFRevisionMul in '..\LIBA\uTofAFRevisionMul.pas',
  UTOFAFREVMODIFCOEF in '..\LIBA\UTOFAFREVMODIFCOEF.PAS',
  utofAfRevPrepaImport in '..\LIBA\utofAfRevPrepaImport.pas',
  uTofAfRevRegulFacture in '..\LIBA\uTofAfRevRegulFacture.pas',
  uTofAfRevSelFormule in '..\LIBA\uTofAfRevSelFormule.pas',
  utofAfRevTraitFormule in '..\LIBA\utofAfRevTraitFormule.pas',
  UTOFAFSAISDATE in '..\LIBA\UTOFAFSAISDATE.PAS',
  UTOFAFTABBORDOLE in '..\LIBA\UTOFAFTABBORDOLE.PAS',
  UTofAfTableauBord in '..\LIBA\UTofAfTableauBord.pas',
  UTofAFTiers_Mul in '..\liba\UTofAFTiers_Mul.pas',
  UtofafTiers_Rech in '..\LIBA\UtofafTiers_Rech.pas',
  UtofAfTRADUCCHAMPLIBRE in '..\LIBA\UtofAfTRADUCCHAMPLIBRE.pas',
  uTofAFValIndiceMul in '..\LIBA\uTofAFValIndiceMul.PAS',
  UTofAfVentesCube in '..\LIBA\UTofAfVentesCube.pas',
  UTofAfVentilana in '..\LIBA\UTofAfVentilana.pas',
  UTOFAFVISAPIECPRO_MUL in '..\LIBA\UTOFAFVISAPIECPRO_MUL.PAS',
  UTofAjustStock in '..\LIB\UTofAjustStock.pas',
  UTofAnnulApp in '..\LIBBTP\UTofAnnulApp.pas',
  UTofAppelConso in '..\LIBBTP\UTofAppelConso.pas',
  UTofAppels in '..\LIBBTP\UTofAppels.pas',
  UTofArticles_Aff in '..\LIBA\UTofArticles_Aff.pas',
  UTofArticleTiers in '..\LIB\UTofArticleTiers.pas',
  UTofBaseEtats in '..\LIBA\UTofBaseEtats.pas',
  UTofBatchVISA in '..\LIB\UTofBatchVISA.pas',
  UTOFBtAnalDev in '..\LIBBTP\UTOFBtAnalDev.PAS',
  UTOFBTArticle_mul in '..\LIBBTP\UTOFBTArticle_mul.pas',
  UtofBTChangeCodeArt in '..\LIBBTP\UtofBTChangeCodeArt.pas',
  UTOFBTClotureDev in '..\LIBBTP\UTOFBTClotureDev.pas',
  UTofBTCodeAffaire in '..\LIBBTP\UTofBTCodeAffaire.pas',
  UTOFBTCOMPLIGNE in '..\LIBBTP\UTOFBTCOMPLIGNE.PAS',
  UTOFBTCOMPLIOUV in '..\LIBBTP\UTOFBTCOMPLIOUV.PAS',
  UTofBTEditDocDiff in '..\LIBBTP\UTofBTEditDocDiff.pas',
  UtofBTMemorisation in '..\LIB\UtofBTMemorisation.pas',
  UtofBTPaieAnnul in '..\LIBBTP\UtofBTPaieAnnul.pas',
  UTofBTPaieGener in '..\LIBBTP\UTofBTPaieGener.pas',
  UTofBTPaieGenerChoix in '..\LIBBTP\UTofBTPaieGenerChoix.pas',
  UTOFBTPARIMPDOC in '..\LIBBTP\UTOFBTPARIMPDOC.PAS',
  UTOFBTPIECERG in '..\LIBBTP\UTOFBTPIECERG.pas',
  UTofBtSaisieVar in '..\LIBBTP\UTofBtSaisieVar.pas',
  UTofCegidLibreTiersCom in '..\LIB\UTofCegidLibreTiersCom.pas',
  UTofCegidPCI in '..\LIB\UTofCegidPCI.pas',
  UtofChainages in '..\..\PROSPECT\Lib\UtofChainages.pas',
  UtofCltVisites in '..\..\PROSPECT\Lib\UtofCltVisites.pas',
  UtofCodeCpta in '..\LIB\UtofCodeCpta.pas',
  uTOFComm in '..\..\COMMUN\LIB\uTOFComm.PAS',
  UtofConsoEtat in '..\LIB\UtofConsoEtat.pas',
  UTofConsultStock in '..\LIB\UTofConsultStock.pas',
  UTOFCONTACT in '..\..\COMMUN\LIB\UTOFCONTACT.PAS',
  UtofCONTACTS_TV in '..\..\PROSPECT\Lib\UtofCONTACTS_TV.PAS',
  UtofCubeActions in '..\..\PROSPECT\LIB\UtofCubeActions.pas',
  UtofCubeOPERATIONS in '..\..\prospect\Lib\UtofCubeOPERATIONS.PAS',
  UtofCubePerspectives in '..\..\PROSPECT\Lib\UtofCubePerspectives.pas',
  UtofCubePropositions in '..\..\PROSPECT\Lib\UtofCubePropositions.pas',
  UTofCubeProspect in '..\..\PROSPECT\Lib\UTofCubeProspect.pas',
  UTofDispo_Dim in '..\LIB\UTofDispo_Dim.pas',
  UTofDispo_glo in '..\LIB\UTofDispo_glo.pas',
  UTofDispo_Mul in '..\LIB\UTofDispo_Mul.pas',
  UTofDispoEtat in '..\LIB\UTofDispoEtat.pas',
  UtofEdiBI in '..\LIBBTP\UtofEdiBI.pas',
  UtofEditionBI in '..\LIBBTP\UtofEditionBI.pas',
  UTofEditStat in '..\LIB\UTofEditStat.pas',
  UTofEtatsActivite in '..\LIBA\UTofEtatsActivite.pas',
  UTofEtatsAffaire in '..\LIBA\UTofEtatsAffaire.pas',
  UTofEtiqArt in '..\LIB\UTofEtiqArt.pas',
  UTofEtiqCli in '..\LIB\UTofEtiqCli.pas',
  BTTrsConso_TOF in '..\LibBTP\BTTrsConso_TOF.pas',
  UtofFicheProspect in '..\..\PROSPECT\Lib\UtofFicheProspect.pas',
  UtofGCAcomptes in '..\LIB\UtofGCAcomptes.pas',
  UTofGCAFF_Mul in '..\LIB\UTofGCAFF_Mul.pas',
  UTofGcArtCom_Tiers in '..\LIB\UTofGcArtCom_Tiers.pas',
  UTofGcArticle_Mul in '..\LIB\UTofGcArticle_Mul.pas',
  UTofGCCATALOGU_MUL in '..\LIB\UTofGCCATALOGU_MUL.pas',
  UtofGcComptesHT in '..\lib\UtofGcComptesHT.pas',
  UTOFGCcptadiff in '..\LIB\UTOFGCcptadiff.pas',
  UTofGCDatePiece in '..\LIB\UTofGCDatePiece.pas',
  UTOFGCENCOURS in '..\LIB\UTOFGCENCOURS.PAS',
  UTofBTFamHier in '..\..\..\MODIFFV078\gescom\LibBTP\UTofBTFamHier.pas',
  UTofGCFournisseur_Mul in '..\..\PROSPECT\Lib\UTofGCFournisseur_Mul.pas',
  UTofGcListeInv_mul in '..\LIB\UTofGcListeInv_mul.pas',
  UTofGcModifLot in '..\LIB\UTofGcModifLot.pas',
  UTofBTMouvStk in '..\Lib\UTofBTMouvStk.pas',
  UtofGcMulPEC in '..\LIB\UtofGcMulPEC.pas',
  UTofGcMulSupprArt in '..\LIB\UTofGcMulSupprArt.pas',
  UTofGcMultiSelArt in '..\LIB\UTofGcMultiSelArt.pas',
  UtofGCOuvFerm in '..\LIB\UtofGCOuvFerm.pas',
  UTofGCPieceArtLie in '..\LIB\UTofGCPieceArtLie.pas',
  UTofGcPieceCours_Tier in '..\LIB\UTofGcPieceCours_Tier.pas',
  UTofGCTiers_ModifLot in '..\lib\UTofGCTiers_ModifLot.pas',
  UTofGCTIERS_MUL in '..\LIB\UTofGCTIERS_MUL.PAS',
  UTOFGCTRAITEADRESSE in '..\LIB\UTOFGCTRAITEADRESSE.pas',
  UTofGcUtilisationArtDim in '..\LIB\UTofGcUtilisationArtDim.pas',
  UTofGeneManPiece in '..\LIB\UTofGeneManPiece.pas',
  UTofGenePiece in '..\LIB\UTofGenePiece.pas',
  UtofGenere_Actions in '..\..\PROSPECT\Lib\UtofGenere_Actions.pas',
  UtofGridFournisseur in '..\LIB\UtofGridFournisseur.pas',
  UTofHoraireStd in '..\LIBA\UTofHoraireStd.pas',
  UtofInfosPlanning in '..\..\PROSPECT\Lib\UtofInfosPlanning.pas',
  UTofInitStock in '..\LIB\UTofInitStock.pas',
  UTOFInvPerm in '..\LIB\UTOFInvPerm.pas',
  utofLanceParser in '..\LIBA\utofLanceParser.pas',
  UTofListeInv in '..\LIB\UTofListeInv.pas',
  UTOFListeInvPrep in '..\LIB\UTOFListeInvPrep.pas',
  UTOFListeInvVal in '..\LIB\UTOFListeInvVal.pas',
  UtofMailing in '..\..\PROSPECT\LIB\UtofMailing.pas',
  UtofMailingAff in '..\..\PROSPECT\LIB\UtofMailingAff.pas',
  UtofMBOEdtCli_mode in '..\LIBM\UtofMBOEdtCli_mode.pas',
  UtofGCFouMul_mode in '..\libm\UtofGCFouMul_mode.pas',
  UtofMBOParamDim in '..\LIBM\UtofMBOParamDim.pas',
  UTOFMBOVALIDEMODELE in '..\LIBM\UTOFMBOVALIDEMODELE.PAS',
  UTofMBOVentilana in '..\LIBM\UTofMBOVentilana.pas',
  utofmouvinterne_mul in '..\LIB\utofmouvinterne_mul.pas',
  utofmouvStkEx in '..\LIB\utofmouvStkEx.pas',
  UTofNomen in '..\LIB\UTofNomen.pas',
  UtofOper_etat in '..\..\PROSPECT\Lib\UtofOper_etat.pas',
  UTofOperations in '..\..\PROSPECT\Lib\UTofOperations.pas',
  UtofOPERATIONS_TV in '..\..\PROSPECT\LIB\UtofOPERATIONS_TV.PAS',
  UTofOptionEdit in '..\LIB\UTofOptionEdit.pas',
  UTofParamCL in '..\..\PROSPECT\Lib\UTofParamCL.pas',
  UTOFPARAMONGLETS in '..\..\PROSPECT\LIB\UTOFPARAMONGLETS.PAS',
  UtofParamTableCompl in '..\..\PROSPECT\Lib\UtofParamTableCompl.pas',
  UTofParfou in '..\LIB\UTofParfou.pas',
  UTofParSuspect in '..\..\PROSPECT\Lib\UTofParSuspect.pas',
  UTofPerspective in '..\..\PROSPECT\Lib\UTofPerspective.pas',
  UtofPerspective_etat in '..\..\PROSPECT\Lib\UtofPerspective_Etat.pas',
  UTofPerspective_His in '..\..\PROSPECT\Lib\UTofPerspective_His.pas',
  UtofPerspective_TV in '..\..\PROSPECT\Lib\UtofPerspective_TV.pas',
  UTofPerspective_Var in '..\..\PROSPECT\Lib\UTofPerspective_Var.pas',
  UtofPgImportFic in '..\..\COMMUN\LIB\UtofPgImportFic.pas',
  UTofPiece in '..\LIB\UTofPiece.pas',
  UTofPiedPort in '..\LIB\UTofPiedPort.pas',
  UTofPrixRevient in '..\LIB\UTofPrixRevient.pas',
  UtofProdCommercial in '..\LIB\UtofProdCommercial.pas',
  UTofProjets in '..\..\PROSPECT\Lib\UTofProjets.pas',
  UTofProposToAffaire in '..\LIBA\UTofProposToAffaire.pas',
  UtofPros_ssactions in '..\..\PROSPECT\Lib\UtofPros_ssactions.pas',
  UTofProspect_Mul in '..\..\PROSPECT\LIB\UTofProspect_Mul.pas',
  UtofProspect_TV in '..\..\PROSPECT\Lib\UtofProspect_TV.pas',
  UtofProspectCompl in '..\..\PROSPECT\Lib\UtofProspectCompl.pas',
  UtofProspectConf in '..\..\PROSPECT\Lib\UtofProspectConf.pas',
  UtofPtfPiece in '..\LIB\UtofPtfPiece.pas',
  UtofRECHDOCGED in '..\..\PROSPECT\LIB\UtofRECHDOCGED.PAS',
  UTofReportActions in '..\..\PROSPECT\Lib\UTofReportActions.pas',
  UTofResHistoValo in '..\LIBA\UTofResHistoValo.pas',
  UtofRessource_Mul in '..\LIBA\UtofRessource_Mul.pas',
  UTOFREVAL_RESS_MUL in '..\LIBA\UTOFREVAL_RESS_MUL.PAS',
  UtofRTActions_MulChai in '..\..\PROSPECT\LIB\UtofRTActions_MulChai.pas',
  UtofRTAffaire_TV in '..\..\PROSPECT\LIB\UtofRTAffaire_TV.pas',
  UtofRTAnaProsp in '..\..\PROSPECT\Lib\UtofRTAnaProsp.pas',
  UtofRTAnnuaire in '..\..\PROSPECT\Lib\UtofRTAnnuaire.pas',
  UtofRTAttachPiece in '..\..\prospect\Lib\UtofRTAttachPiece.pas',
  UTOFRTCONCURRENT_MUL in '..\..\PROSPECT\Lib\UTOFRTCONCURRENT_MUL.PAS',
  UtofRTCourrier in '..\..\PROSPECT\Lib\UtofRTCourrier.pas',
  UTofRTDoublons in '..\..\PROSPECT\Lib\UTofRTDoublons.pas',
  UTOFRTFICHESUSPECT in '..\..\PROSPECT\Lib\UTOFRTFICHESUSPECT.PAS',
  UtofRTInfosRespons in '..\..\PROSPECT\Lib\UtofRtInfosRespons.pas',
  UTofRTParamPlanning in '..\..\PROSPECT\Lib\UTofRTParamPlanning.PAS',
  UtofRTPiece_TV in '..\..\PROSPECT\LIB\UtofRTPiece_TV.pas',
  UtofRTPiecesOper in '..\..\PROSPECT\LIB\UtofRTPiecesOper.pas',
  UTofRTProspect_ModifLot in '..\..\PROSPECT\Lib\UTofRTProspect_ModifLot.pas',
  UtofRTSuppressionTiers in '..\..\PROSPECT\LIB\UtofRTSuppressionTiers.pas',
  UTOFRTSUSPECTS_CUBE in '..\..\PROSPECT\Lib\UTOFRTSUSPECTS_CUBE.PAS',
  UtofRTTIERS_RECH in '..\..\PROSPECT\Lib\UtofRTTiers_Rech.pas',
  UTofSaisieAvanc in '..\LIB\UTofSaisieAvanc.pas',
  UTofSaisiLot in '..\Lib\UTofSaisiLot.pas',
  UtofSelectDim in '..\LIB\UtofSelectDim.pas',
  UtofSuiviActivite in '..\..\PROSPECT\LIB\UtofSuiviActivite.pas',
  uTofSuiviPiece in '..\LIB\uTofSuiviPiece.pas',
  UTofSuspect_Mul in '..\..\PROSPECT\LIB\UTofSuspect_Mul.pas',
  UTofTarif in '..\LIB\UTofTarif.pas',
  UTofTarifArt_Mul in '..\LIB\UTofTarifArt_Mul.pas',
  UtofTiersCTI_Mul in '..\..\PROSPECT\LIB\UtofTiersCTI_Mul.pas',
  UtofTiersRecherche in '..\LIB\UtofTiersRecherche.pas',
  UTofTTPeriode in '..\LIB\UTofTTPeriode.pas',
  UtofTVEncours in '..\..\PROSPECT\Lib\UtofTVEncours.pas',
  UtofTypesChainages in '..\..\PROSPECT\Lib\UtofTypesChainages.pas',
  UTofValidInv in '..\Lib\UTofValidInv.pas',
  Utomaction in '..\..\PROSPECT\LIB\Utomaction.pas',
  Utomactionchaine in '..\..\PROSPECT\LIB\Utomactionchaine.pas',
  UTomActivitePaie in '..\LIBA\UTomActivitePaie.pas',
  UTOMADRESSES in '..\LIB\UTOMADRESSES.PAS',
  UTomAffaire in '..\LIBA\UTomAffaire.pas',
  UTomAffairePiece in '..\LIBA\UTomAffairePiece.pas',
  uTomAfIndice in '..\LIBA\uTomAfIndice.PAS',
  UTomAFPLANNING in '..\LIBA\UTomAFPLANNING.PAS',
  uTomAfPublication in '..\LIBA\uTomAfPublication.pas',
  uTomAfRevParamFormule in '..\LIBA\uTomAfRevParamFormule.pas',
  uTomAfValIndice in '..\LIBA\uTomAfValIndice.pas',
  UTomArticle in '..\LIB\UTomArticle.pas',
  UTomArticleTiers in '..\lib\UTomArticleTiers.pas',
  UTOMBanque in '..\..\COMMUN\LIB\UTOMBanque.pas',
  UTOMBtEtat in '..\LIBBTP\UTOMBtEtat.pas',
  UTOMBTEVENEMENT in '..\LIBBTP\UTOMBTEVENEMENT.pas',
  UTOMCalendrierRegle in '..\LIBA\UTOMCalendrierRegle.pas',
  UTomCodeCpta in '..\LIB\UTomCodeCpta.pas',
  uTOMComm in '..\..\COMMUN\LIB\uTOMComm.pas',
  UTomCommercial in '..\LIB\UTomCommercial.pas',
  UTomCompetence in '..\LIBA\UTomCompetence.pas',
  UTomContact in '..\..\COMMUN\LIB\UTomContact.pas',
  UTomDimMasque in '..\LIB\UTomDimMasque.pas',
  UTOMEmplacement in '..\lib\UTOMEmplacement.pas',
  UTomEtabliss in '..\..\COMMUN\lib\UTomEtabliss.pas',
  UTomFerie in '..\LIBA\UTomFerie.pas',
  UtomLiensOle in '..\..\COMMUN\LIB\UtomLiensOle.pas',
  UTomMODEPAIE in '..\..\COMMUN\lib\UTomMODEPAIE.pas',
  UTomModeregl in '..\..\COMMUN\lib\UTomModeregl.pas',
  UTOMNaturePrest in '..\LIBBTP\UTOMNaturePrest.PAS',
  UTomNomen in '..\LIB\UTomNomen.pas',
  UTomOperation in '..\..\PROSPECT\Lib\UTomOperation.pas',
  UtomParActions in '..\..\PROSPECT\Lib\UtomParActions.pas',
  UtomParChainages in '..\..\PROSPECT\Lib\UtomParChainages.pas',
  UTomParPiece in '..\lib\UTomParPiece.pas',
  UTOMPERSPECTIVE in '..\..\PROSPECT\LIB\UTOMPERSPECTIVE.PAS',
  UTomPiece in '..\LIB\UTomPiece.pas',
  UtomProjet in '..\..\PROSPECT\Lib\UtomProjet.pas',
  UTomRessource in '..\LIBA\UTomRessource.pas',
  UTomRessourcePr in '..\LIBA\UTomRessourcePr.pas',
  UTomRIB in '..\..\COMMUN\lib\UTomRIB.pas',
  UtomRTEtatPlan in '..\..\PROSPECT\Lib\UtomRTEtatPlan.pas',
  UTomStock in '..\LIB\UTomStock.pas',
  UTomSuspect in '..\..\PROSPECT\LIB\UTomSuspect.pas',
  UTomTiers in '..\LIB\UTomTiers.pas',
  UTOMUTILISAT in '..\..\COMMUN\lib\UTOMUTILISAT.pas',
  UTomVariable in '..\LIBBTP\UTomVariable.pas',
  Utot_btnaturedoc in '..\LIBBTP\Utot_btnaturedoc.pas',
  UTotAff in '..\LIBA\UTotAff.pas',
  UTotGC in '..\LIB\UTotGC.pas',
  UTOTRT in '..\..\PROSPECT\Lib\UTotRT.pas',
  uTreeTobFrame in '..\..\COMMUN\LIB\uTreeTobFrame.pas' {FFrameTreeTob: TFrame},
  uVoirSuiviPiece in '..\LIB\uVoirSuiviPiece.pas',
  ValidateInv in '..\LIB\ValidateInv.pas' {ValidateForm},
  ValideDecisionAch in '..\LIBBTP\ValideDecisionAch.pas',
  Ventana in '..\..\COMMUN\LIB\Ventana.pas',
  VentesCubeTof in '..\LIB\VentesCubeTof.pas',
  Ventil in '..\..\COMPTA\LIBC\Ventil.pas' {FVentil},
  VentilCpta in '..\LIB\VentilCpta.pas',
  VerifAuxiTiers in '..\LIB\VerifAuxiTiers.PAS',
  VerifNatErrImp in '..\LIB\VerifNatErrImp.PAS',
  Vierge {FVierge},
  VisuLog in '..\LIB\VisuLog.pas',
  wBlocNote_Tof in '..\..\COMMUN\LIB\wBlocNote_Tof.pas',
  wCommuns in '..\..\COMMUN\LIB\wCommuns.pas',
  wJetons in '..\..\COMMUN\Lib\wJetons.pas',
  Wmnu in '..\..\COMMUN\LIB\Wmnu.PAS',
  WPARAM in '..\..\COMMUN\LIB\WPARAM.PAS',
  WPROPERTIES_TOF in '..\..\COMMUN\LIB\WPROPERTIES_TOF.PAS',
  wrapport in '..\..\COMMUN\Lib\wrapport.pas',
  WRAPPORT_TOF in '..\..\COMMUN\LIB\WRAPPORT_TOF.PAS',
  WTOF in '..\LIBW\WTOF.PAS',
  WTOM in '..\LIBW\WTOM.PAS',
  YDocuments_Tom in '..\..\COMMUN\Lib\YDocuments_Tom.pas',
  YFiles_Tom in '..\..\COMMUN\Lib\YFiles_Tom.pas',
  YMessageDetailDestinataire in '..\..\DP\LIB\YMessageDetailDestinataire.pas' {FMsgDetailDest},
  YNewMessage in '..\..\DP\LIB\YNewMessage.pas' {FNewMessage},
  YRechercherDestinataire in '..\..\DP\LIB\YRechercherDestinataire.pas' {FRechercherDestinataire},
  ZCompte in '..\..\COMPTA\LibC\ZCompte.pas',
  ZoomEdtAffaire in '..\LIBA\ZoomEdtAffaire.pas',
  ZoomEdtGescom in '..\Lib\ZoomEdtGescom.pas',
  ZoomEdtProspect in '..\..\PROSPECT\Lib\ZoomEdtProspect.pas',
  UtofBTFAMRES_MUL in '..\Libbtp\UtofBTFAMRES_MUL.pas',
  UtomBTFAMRES in '..\LIBBTP\UtomBTFAMRES.pas',
  BTSERVICES_TOF in '..\LIBBTP\BTSERVICES_TOF.PAS',
  UTOFBTPLANNINGEXEMPLE in '..\Libbtp\UTOFBTPLANNINGEXEMPLE.PAS',
  UTOMBTPARAMPLANNING in '..\LIBBTP\UTOMBTPARAMPLANNING.PAS',
  HRListeIcone in '..\LIBBTP\HRListeIcone.pas' {FicheIcone},
  UTofBtAffAppel in '..\LIBBTP\UTofBtAffAppel.pas',
  UtofBtSuppEvent in '..\LIBBTP\UtofBtSuppEvent.pas',
  BTResContrats_TOF in '..\LIBBTP\BTResContrats_TOF.PAS',
  BTControleCBT_TOF in '..\LIBBTP\BTControleCBT_TOF.PAS',
  UtilOutilsLivraisons in '..\LIBBTP\UtilOutilsLivraisons.pas' {FOutilsLivr},
  BTAPPLICDETAILOUV_TOF in '..\LIBBTP\BTAPPLICDETAILOUV_TOF.pas',
  uBtpChargeTob in '..\Libbtp\uBtpChargeTob.pas',
  BTREGLPIECE_MUL_TOF in '..\LIBBTP\BTREGLPIECE_MUL_TOF.pas',
  BTOUVRAGE_MUL_TOF in '..\LIBBTP\BTOUVRAGE_MUL_TOF.pas',
  BTOUVRAGE_PEDT_TOF in '..\LibBTP\BTOUVRAGE_PEDT_TOF.pas',
  BTISFACTURE_TOF in '..\LIBBTP\BTISFACTURE_TOF.pas',
  BTACCEPTAFF_MUL_TOF in '..\LibBTP\BTACCEPTAFF_MUL_TOF.pas',
  BTMODELHEBDO_TOF in '..\LIBBTP\BTMODELHEBDO_TOF.pas',
  UtilModeleConso in '..\LIBBTP\UtilModeleConso.pas',
  BTSAISIEHEBDO_TOF in '..\LIBBTP\BTSAISIEHEBDO_TOF.pas',
  UtilConsultFour in '..\LIBBTP\UtilConsultFour.pas',
  BTFOURNMULTI_MUL_TOF in '..\LIBBTP\BTFOURNMULTI_MUL_TOF.pas',
  BTMULGRIDCATALOG_TOF in '..\LIBBTP\BTMULGRIDCATALOG_TOF.pas',
  BTPAREDCONS_TOF in '..\LIBBTP\BTPAREDCONS_TOF.pas',
  BTDECISIONACHOPT_TOF in '..\libbtp\BTDECISIONACHOPT_TOF.pas',
  UtilgepBtp in '..\LIBBTP\UtilgepBtp.pas',
  UtofBTTaches in '..\LIBBTP\UtofBTTaches.PAS',
  UtofBTModeleTache in '..\LIBBTP\UtofBTModeleTache.PAS',
  BTMajStruct in '..\LIBBTP\BTMajStruct.pas',
  PiecesRecalculs in '..\LIBBTP\PiecesRecalculs.pas',
  BTRECALCPIECEUNI in '..\LIBBTP\BTRECALCPIECEUNI.pas',
  BTRESTDUAFF_TOF in '..\LIBBTP\BTRESTDUAFF_TOF.PAS',
  BTRECALCPIECE_MUL_TOF in '..\LIBBTP\BTRECALCPIECE_MUL_TOF.pas',
  RECALCPIECE_RAP_TOF in '..\LibBTP\RECALCPIECE_RAP_TOF.pas',
  UCdeBatiprix in '..\LIBBTP\UCdeBatiprix.pas' {FCdeBatiprix},
  UintegreBatiprix in '..\LIBBTP\UintegreBatiprix.pas' {FIntegreBatiprix},
  UtilBatiprixFile in '..\LibBTP\UtilBatiprixFile.pas',
  UtilGestionChaine in '..\LibBTP\UtilGestionChaine.pas',
  BTRefCdeBatiprix_TOF in '..\LibBTP\BTRefCdeBatiprix_TOF.pas',
  UtilBlocage in '..\LIBBTP\UtilBlocage.pas',
  factligneBase in '..\LIBBTP\factligneBase.pas',
  BTSAISIEAVANC_TOF in '..\LibBTP\BTSAISIEAVANC_TOF.pas',
  BTSELFAC_MUL_TOF in '..\LibBTP\BTSELFAC_MUL_TOF.PAS',
  BTGENFACTURE in '..\LIBBTP\BTGENFACTURE.pas',
  UTOFBTMEMORIS_MUL in '..\LibBTP\UTOFBTMEMORIS_MUL.pas',
  BTCHOIXAPPLICAVAN_TOF in '..\LibBTP\BTCHOIXAPPLICAVAN_TOF.PAS',
  TobUtil in '..\..\CommunBTP\LIB\D5\TobUtil.pas',
  UtofBtTypeRes in '..\LibBTP\UtofBtTypeRes.pas',
  BTMUL_TOF in '..\LibBTP\BTMUL_TOF.PAS',
  UtofBTTYPERES_MUL in '..\LibBTP\UtofBTTYPERES_MUL.pas',
  BTPREPSELFAC_MUL_TOF in '..\LibBTP\BTPREPSELFAC_MUL_TOF.PAS',
  ProfileArt_Mul in '..\LibBTP\ProfileArt_Mul.pas',
  UProcGen in '..\..\Treso\Lib\UProcGen.pas',
  TImpFic in '..\..\Treso\Lib\TImpFic.pas',
  CPTypeCons in '..\..\compta\Lib4\CPTypeCons.pas',
  ULibTrSynchro in '..\..\compta\LibN\ULibTrSynchro.pas',
  Commun in '..\..\Treso\Lib\Commun.pas',
  Constantes in '..\..\Treso\Lib\Constantes.pas',
  CPProcGen in '..\..\compta\Lib4\CPProcGen.pas',
  KPMGUtil in '..\..\prospect\Lib\KPMGUtil.PAS',
  GCOuvertureGEP in '..\Lib\GCOuvertureGEP.pas',
  UTofRess_Occup in '..\..\prospect\Lib\UTofRess_Occup.pas',
  UTOFDOCEXTERNE in '..\LibA\UTOFDOCEXTERNE.pas',
  UTOMDOCEXTERNE in '..\LibA\UTOMDOCEXTERNE.pas',
  CPSTRUCTURE_TOF in '..\..\compta\LibN\CPSTRUCTURE_TOF.PAS',
  CPVersion in '..\..\compta\Lib4\CPVersion.pas',
  CritEdt in '..\..\compta\LibC\CritEdt.pas',
  uYFILESTD2 in '..\..\ImportDP\lib\uYFILESTD2.pas',
  UtilEAffaire in '..\LIBA\UtilEAffaire.pas',
  galSystem in '..\..\Cegidpgi\Lib\galSystem.pas',
  galFileTools in '..\..\Cegidpgi\Lib\galFileTools.pas',
  WPARAMFONCTION in '..\libw\WPARAMFONCTION.PAS',
  EntPaie in '..\..\paie\lib\EntPaie.pas',
  PGRepertoire in '..\..\paie\lib\PGRepertoire.pas',
  UAFO_Affaire in '..\LibA\UAFO_Affaire.pas',
  AnnOutils in '..\..\DP\Lib\AnnOutils.pas',
  ReformateChamp in '..\..\DP\Lib\ReformateChamp.pas',
  UDroitsAcces in '..\..\commun\Lib\UDroitsAcces.pas',
  dpTofAnnusel in '..\..\DP\Lib\dpTofAnnusel.pas',
  dpOutils in '..\..\DP\Lib\dpOutils.pas',
  UTOFZonesLibres in '..\..\DP\Lib\UTOFZonesLibres.pas',
  uObjEtats in '..\..\Treso\Lib\uObjEtats.pas',
  dpTOFVisuReleve in '..\..\DP\Lib\dpTOFVisuReleve.pas',
  uLibPointage in '..\..\compta\LibN\uLibPointage.pas',
  AssistCiblageVersOperation in '..\..\PROSPECT\LIB\AssistCiblageVersOperation.pas' {FAssistCiblageVersOperation},
  UTOFCIBLAGE_TOF in '..\..\prospect\Lib\UTOFCIBLAGE_TOF.PAS',
  uTofRTTOPCONTACT_TOF in '..\..\prospect\Lib\uTofRTTOPCONTACT_TOF.PAS',
  UtofMixte in '..\..\prospect\Lib\UtofMixte.pas',
  utofRTTOPTIERSCON_TOF in '..\..\prospect\Lib\utofRTTOPTIERSCON_TOF.PAS',
  UtofRTTOPSUSCON_TOF in '..\..\prospect\Lib\UtofRTTOPSUSCON_TOF.PAS',
  UTofRTTOPCIBLE in '..\..\prospect\Lib\UTofRTTOPCIBLE.PAS',
  UTofRTTOPTIERS_TOF in '..\..\prospect\Lib\UTofRTTOPTIERS_TOF.PAS',
  uTofRTCIBLESUS_TOF in '..\..\prospect\Lib\uTofRTCIBLESUS_TOF.PAS',
  UTOFVISAMUL_TOF in '..\..\prospect\Lib\UTOFVISAMUL_TOF.PAS',
  UTOFLISTEPOURVISA_TOF in '..\..\prospect\Lib\UTOFLISTEPOURVISA_TOF.PAS',
  UTofListeVisaCon_TOF in '..\..\prospect\Lib\UTofListeVisaCon_TOF.PAS',
  UtomCIBLAGE in '..\..\prospect\Lib\UtomCIBLAGE.PAS',
  UtofRTRECHMIXTE_TOF in '..\..\prospect\Lib\UtofRTRECHMIXTE_TOF.PAS',
  UtofRTSUSPECTPROSPECT in '..\..\prospect\Lib\UtofRTSUSPECTPROSPECT.PAS',
  UtofRTDUPLIMPORT in '..\..\prospect\Lib\UtofRTDUPLIMPORT.PAS',
  UtofRECUPSUSPECT in '..\..\prospect\Lib\UtofRECUPSUSPECT.PAS',
  UtofRTSUPPRSUSP in '..\..\prospect\Lib\UtofRTSUPPRSUSP.PAS',
  UtofPersp_ModifLot in '..\..\prospect\Lib\UtofPersp_ModifLot.pas',
  UtofAct_ModifLot in '..\..\prospect\Lib\UtofAct_ModifLot.pas',
  UtofRTsuiviAction in '..\..\prospect\Lib\UtofRTsuiviAction.pas',
  utofAFANCETRE_GIGA_GRC in '..\LibA\utofAFANCETRE_GIGA_GRC.PAS',
  CtiPcb in '..\..\PROSPECT\LIB\CtiPcb.pas' {Form1},
  UtofAfMajChampsAuto in '..\LibA\UtofAfMajChampsAuto.pas',
  BTStructChampSup in '..\LibBTP\BTStructChampSup.pas',
  YYBUNDLE_TOF in '..\..\commun\Lib\YYBUNDLE_TOF.PAS',
  yalertes_tof in '..\..\commun\Lib\yalertes_tof.pas',
  YALERTes_tom in '..\..\commun\Lib\yalertes_tom.pas',
  BTINFOLIVRAISONS_TOF in '..\LibBTP\BTINFOLIVRAISONS_TOF.PAS',
  BTTVA_TOF in '..\LibBTP\BTTVA_TOF.PAS',
  BTCONFIRMECLOTURE_TOF in '..\LibBTP\BTCONFIRMECLOTURE_TOF.PAS',
  BTIMPDGD_MUL_TOF in '..\LibBTP\BTIMPDGD_MUL_TOF.PAS',
  BTCLOTUREAFF_MUL_TOF in '..\LibBTP\BTCLOTUREAFF_MUL_TOF.PAS',
  BTCLOTUREAFF_TOF in '..\LibBTP\BTCLOTUREAFF_TOF.PAS',
  UTofBTTacheModele in '..\LibBTP\UtofBtTacheModele.pas',
  factdomaines in '..\LibBTP\factdomaines.pas',
  BTAPPELINTCOMPL_TOF in '..\LibBTP\BTAPPELINTCOMPL_TOF.PAS',
  UtilFermeturePiece in '..\LibBTP\UtilFermeturePiece.pas',
  BTCONFIRMEPURCHA_TOF in '..\LibBTP\BTCONFIRMEPURCHA_TOF.PAS',
  BTCONFIRMEPURPIEC_TOF in '..\LibBTP\BTCONFIRMEPURPIEC_TOF.PAS',
  BTCONFIRMPASS_TOF in '..\LibBTP\BTCONFIRMPASS_TOF.PAS',
  BTEPUREAFF_MUL_TOF in '..\LibBTP\BTEPUREAFF_MUL_TOF.PAS',
  BTEPUREPIECE_MUL_TOF in '..\LibBTP\BTEPUREPIECE_MUL_TOF.PAS',
  BTFERMEPIECE_MUL_TOF in '..\LibBTP\BTFERMEPIECE_MUL_TOF.PAS',
  EpurationChantiers in '..\LibBTP\EpurationChantiers.pas',
  EpurationPieces in '..\LibBTP\EpurationPieces.pas',
  FermeturePieces in '..\LibBTP\FermeturePieces.pas',
  UtilEpurePiece in '..\LibBTP\UtilEpurePiece.pas',
  UtilBTPgestChantier in '..\..\extensionCBP\UtilBTPgestChantier.pas',
  BTPGetStructure in '..\..\extensionCBP\BTPGetStructure.pas',
  UtilchampsSup in '..\LibBTP\UtilchampsSup.pas',
  BTPGetVersions in '..\..\extensionCBP\BTPGetVersions.pas',
  uBTPGetDocument in '..\..\extensionCBP\uBTPGetDocument.pas',
  uBTPVerrouilleDossier in '..\..\extensionCBP\uBTPVerrouilleDossier.pas',
  UmetresUtil in '..\..\extensionCBP\UmetresUtil.pas',
  UtilBordereau in '..\..\extensionCBP\UtilBordereau.pas',
  uEntCommun in '..\..\commun\Lib\uEntCommun.pas',
  UtilTOBPiece in '..\LibBTP\UtilTOBPiece.pas',
  UtomAffTiers in '..\LibA\UtomAffTiers.pas',
  ControlIniFile in '..\LibBTP\ControlIniFile.pas',
  UImportLigneExcelFac in '..\LibBTP\UImportLigneExcelFac.pas',
  BTARTPARC_MUL_TOF in '..\LibBTP\BTARTPARC_MUL_TOF.PAS',
  BPARCVERSION_TOF in '..\LibBTP\BPARCVERSION_TOF.PAS',
  UVersionParc in '..\LibBTP\UVersionParc.pas',
  UTofPARCTIERS_MUL in '..\LibBTP\UTofPARCTIERS_MUL.pas',
  BTPARCTIER_TOF in '..\LibBTP\BTPARCTIER_TOF.PAS',
  BTPARCELT_TOF in '..\LibBTP\BTPARCELT_TOF.PAS',
  CLKBtpLib_TLB in '..\..\seria\lib\CLKBtpLib_TLB.pas',
  BTCHANGEVERS_TOF in '..\LibBTP\BTCHANGEVERS_TOF.PAS',
  UserialiseLSE in '..\LibBTP\UserialiseLSE.pas',
  BARTVERSIONNABLE_TOF in '..\LibBTP\BARTVERSIONNABLE_TOF.PAS',
  BTMODIFLISTE_TOF in '..\..\CommunBTP\LIB\BTMODIFLISTE_TOF.PAS',
  UgestionListe in '..\..\CommunBTP\LIB\UgestionListe.pas',
  ctiAlerte in '..\..\commun\Lib\ctiAlerte.pas' {FCtiAlerte},
  ctiInterface in '..\..\commun\Lib\ctiInterface.pas',
  ctiConst in '..\..\commun\Lib\ctiConst.pas',
  BTCHOIXAFFAIRE_TOF in '..\LibBTP\BTCHOIXAFFAIRE_TOF.PAS',
  BTDEMANDECHOIX_TOF in '..\LibBTP\BTDEMANDECHOIX_TOF.PAS',
  BTRESULTCHADET_TOF in '..\LibBTP\BTRESULTCHADET_TOF.PAS',
  UCalculsMetre in '..\LibBTP\UCalculsMetre.pas',
  BTESTFORMULE_TOF in '..\LibBTP\BTESTFORMULE_TOF.PAS',
  BTSAISIEPAGEMETRE_TOF in '..\LibBTP\BTSAISIEPAGEMETRE_TOF.PAS',
  BTDEMANDEDATES_TOF in '..\LibBTP\BTDEMANDEDATES_TOF.PAS',
  UImportLigneNomen in '..\LibBTP\UImportLigneNomen.pas',
  USpecifLSE in '..\LibBTP\USpecifLSE.pas',
  BTACCETU_COMPL_TOF in '..\LibBTP\BTACCETU_COMPL_TOF.PAS',
  UtilParc in '..\LibBTP\UtilParc.pas',
  UdateUtils in '..\LibBTP\UdateUtils.pas',
  BTMINUTEDEV_TOF in '..\LibBTP\BTMINUTEDEV_TOF.PAS',
  UtilpdfCreator in '..\..\DossierEdition\lib\UtilPdfCreator.pas',
  UCotraitance in '..\LibCotraitance\UCotraitance.pas',
  BTAFFAIREINTERV_TOF in '..\LibCotraitance\BTAFFAIREINTERV_TOF.PAS',
  PORT_TOM in '..\LibCotraitance\PORT_TOM.PAS',
  PORTMUL_TOF in '..\LibCotraitance\PORTMUL_TOF.PAS',
  BTAFFAIREFRSGEST_TOF in '..\LibCotraitance\BTAFFAIREFRSGEST_TOF.PAS',
  BTMULAFFAIREINTER_TOF in '..\LibCotraitance\BTMULAFFAIREINTER_TOF.PAS',
  BTMULAFFECTEXTE_TOF in '..\LibCotraitance\BTMULAFFECTEXTE_TOF.PAS',
  UfactExportXLS in '..\LibCotraitance\UfactExportXLS.pas',
  UCotraitanceOuv in '..\LibCotraitance\UCotraitanceOuv.pas',
  UExportPiece in '..\LibCotraitance\UExportPiece.pas',
  Udefexport in '..\LibCotraitance\Udefexport.pas',
  FactDetouvrage in '..\LibBTP\FactDetouvrage.pas',
  BTCHOIXFINSAISIE_TOF in '..\LibCotraitance\BTCHOIXFINSAISIE_TOF.PAS',
  BTEDTBONPAIEMENT_TOF in '..\LibCotraitance\BTEDTBONPAIEMENT_TOF.pas',
  BTINTEGREDOC_TOF in '..\LibCotraitance\BTINTEGREDOC_TOF.pas',
  UtilsEtat in '..\..\CommunBTP\LIB\UtilsEtat.pas',
  UtilsRapport in '..\..\CommunBTP\LIB\UtilsRapport.pas',
  BTPARAMMAIL_TOF in '..\LibCotraitance\BTPARAMMAIL_TOF.pas',
  FactTimbres in '..\LibBTP\FactTimbres.pas',
  TIMBRESPARAM_TOM in '..\LibBTP\TIMBRESPARAM_TOM.PAS',
  BTIMBRESPMUL_TOF in '..\LibBTP\BTIMBRESPMUL_TOF.PAS',
  mscorlib_TLB in '..\..\SPIGAO\mscorlib_TLB.pas',
  BTSpigao in '..\LibBTP\BTSpigao.pas',
  BTSAIREGLTCOTRAIT_TOF in '..\LibBTP\BTSAIREGLTCOTRAIT_TOF.pas',
  BTPIECEINTERV_TOF in '..\LibCotraitance\BTPIECEINTERV_TOF.PAS',
  Edisys_IULM_Core_TLB in '..\..\SPIGAO\Edisys_IULM_Core_TLB.pas',
  Edisys_IULM_Updater_TLB in '..\..\SPIGAO\Edisys_IULM_Updater_TLB.pas',
  Edisys_IULM_Alert_TLB in '..\..\SPIGAO\Edisys_IULM_Alert_TLB.pas',
  Edisys_IULM_AXViewer_TLB in '..\..\SPIGAO\Edisys_IULM_AXViewer_TLB.pas',
  System_TLB in '..\..\SPIGAO\System_TLB.pas',
  System_Windows_Forms_TLB in '..\..\SPIGAO\System_Windows_Forms_TLB.pas',
  Accessibility_TLB in '..\..\SPIGAO\Accessibility_TLB.pas',
  BTMULPIECEINTERV_TOF in '..\LibCotraitance\BTMULPIECEINTERV_TOF.PAS',
  BTPIECEINTERVMUL_TOF in '..\LibCotraitance\BTPIECEINTERVMUL_TOF.PAS',
  UtilsMail in '..\LibCotraitance\UtilsMail.pas',
  DialogEx in '..\LibCotraitance\DialogEx.pas',
  UtilsContacts in '..\LibCotraitance\UtilsContacts.pas',
  UBTPSequenceCpta in '..\..\compta\Lib4\UBTPSequenceCpta.pas',
  UTOMBTTYPEAFFAIRE in '..\LibBTP\UTOMBTTYPEAFFAIRE.pas',
  BTPIECERGCOT_TOF in '..\LibCotraitance\BTPIECERGCOT_TOF.PAS',
  BTPIECERGCAU_TOF in '..\LibCotraitance\BTPIECERGCAU_TOF.PAS',
  UGestionErreurExportLSE in '..\LibBTP\UGestionErreurExportLSE.pas',
  BTGESTERROREXP_TOF in '..\LibBTP\BTGESTERROREXP_TOF.PAS',
  UTofFactConso in '..\LibBTP\UTofFactConso.pas',
  FactRemplTypeLigne in '..\LibBTP\FactRemplTypeLigne.pas',
  BTBLOCFONT_TOF in '..\..\CommunBTP\LIB\BTBLOCFONT_TOF.PAS',
  BTBLOCSELECT_TOF in '..\..\CommunBTP\LIB\BTBLOCSELECT_TOF.PAS',
  UFactgestionAff in '..\LibBTP\UFactgestionAff.pas',
  BTPARAFFDOC_TOF in '..\LibBTP\BTPARAFFDOC_TOF.PAS',
  BTDEMPRIX_MUL_TOF in '..\LibBTP\BTDEMPRIX_MUL_TOF.pas',
  BTVALIDEDEMPRIX_TOF in '..\LibBTP\BTVALIDEDEMPRIX_TOF.pas',
  CREATEDEMPRIX_TOF in '..\LibBTP\CREATEDEMPRIX_TOF.pas',
  UDemandeprix in '..\LibBTP\UDemandeprix.pas',
  BTARTSELDEMPRIX_TOF in '..\LibBTP\BTARTSELDEMPRIX_TOF.PAS',
  CalcMulBTP in '..\LibBTP\CalcMulBTP.pas',
  BPIECEDEMPRIX_MUL_TOF in '..\LibBTP\BPIECEDEMPRIX_MUL_TOF.pas',
  BtImportTARIFXLS in '..\LibBTP\BtImportTARIFXLS.pas',
  UtilAppelFiche in '..\LibBTP\UtilAppelFiche.pas',
  BTLANCEANALYSE_TOF in '..\LibBTP\BTLANCEANALYSE_TOF.pas',
  BTRECALCPMAPNOSTK_TOF in '..\LibBTP\BTRECALCPMAPNOSTK_TOF.pas',
  BCHANGEUNITE_TOF in '..\LibBTP\BCHANGEUNITE_TOF.PAS',
  UCoefsUnite in '..\LibBTP\UCoefsUnite.pas',
  UAuditPerf in '..\..\CommunBTP\LIB\UAuditPerf.pas',
  UtilLine in '..\LibBTP\UtilLine.pas',
  SplashS1 in '..\LibBTP\SplashS1.pas' {Splash_S1},
  RestaureS1 in '..\LibBTP\RestaureS1.pas' {Restaure_S1},
  UtilActionComSx in '..\LIBBTP\UtilActionComSx.pas',
  OuvreExo in '..\..\compta\LibC\OuvreExo.pas' {OuvExo},
  CLOTURE in '..\..\compta\LibC\Cloture.pas' {FCloS},
  BTWebIE in '..\LibBTP\BTWebIE.pas' {FBTWebIE},
  CPTEUTIL in '..\..\compta\Lib4\Cpteutil.pas',
  tcalccum in '..\..\compta\Lib4\tCalcCum.pas',
  ParaClo in '..\..\compta\LibC\ParaClo.pas' {ParamClo},
  ULIBCLOTURE in '..\..\compta\LibN\ULIBCLOTURE.pas',
  BTPARAMSOCGEN_TOF in '..\LIBBTP\BTPARAMSOCGEN_TOF.pas',
  BTPARSOCCPTAGS1_TOF in '..\LibBTP\BTPARSOCCPTAGS1_TOF.pas',
  BTCLOTUREEX_TOF in '..\LIBBTP\BTCLOTUREEX_TOF.pas',
  BTCPTPIECE_S1_TOF in '..\LibBTP\BTCPTPIECE_S1_TOF.pas',
  uLibRevision in '..\..\compta\LibN\uLibRevision.pas',
  BalSit in '..\..\compta\LibN\BalSit.pas',
  AssistExport in '..\LibBTP\AssistExport.pas' {FAssistExport},
  UtilInterComsx in '..\LibBTP\UtilInterComsx.pas',
  BTAssistImport in '..\LibBTP\BTAssistImport.pas' {FBTAssistImport},
  UApplication in '..\LibBTP\UApplication.pas',
  AssistParamSocBtp in '..\LIBBTP\AssistParamSocBtp.pas' {FassistParamSoc},
  galPatience in '..\..\Cegidpgi\Lib\galPatience.pas' {FPatience},
  uPGFnWorkRh in '..\..\paie\lib\uPGFnWorkRh.pas',
  BTAFFCHANGETIER_TOF in '..\LibBTP\BTAFFCHANGETIER_TOF.PAS',
  BTREGLSOUSTRAIT_TOF in '..\LibCotraitance\BTREGLSOUSTRAIT_TOF.PAS',
  BETATPREPPAIE_TOF in '..\LibBTP\BETATPREPPAIE_TOF.pas',
  BTSAISIERESTDEP_TOF in '..\LibBTP\BTSAISIERESTDEP_TOF.pas',
  UDossierVP in '..\Lien VP\UDossierVP.pas',
  UEchangeVP in '..\Lien VP\UEchangeVP.pas',
  UFicheLienVP in '..\Lien VP\UFicheLienVP.pas' {FFicheTestVP},
  ULienVP in '..\Lien VP\ULienVP.pas',
  BTGENODANAL_TOF in '..\..\LibODANAL\BTGENODANAL_TOF.PAS',
  UtilsTOB in '..\..\CommunBTP\LIB\UtilsTOB.pas',
  BTCONSULTODANAL_TOF in '..\..\LibODANAL\BTCONSULTODANAL_TOF.PAS',
  UMenusNeg in '..\LigNegoce\UMenusNeg.pas',
  BTREFUS_TOF in '..\LibBTP\BTREFUS_TOF.PAS',
  BTSELFACNEG_MUL_TOF in '..\LigNegoce\BTSELFACNEG_MUL_TOF.PAS',
  UtilLivraisonNEG in '..\LigNegoce\UtilLivraisonNEG.pas',
  BTPIECETIERS_MUL_TOF in '..\LigNegoce\BTPIECETIERS_MUL_TOF.PAS',
  MenuDisp in '..\Mobilite\Lib\MenuDisp.pas' {FMenuDisp: TDataModule},
  BTAPPELPARRESS_TOF in '..\Mobilite\Lib\BTAPPELPARRESS_TOF.pas',
  BTMESINTERV_TOF in '..\Mobilite\Lib\BTMESINTERV_TOF.pas',
  UtilScreen in '..\Mobilite\Lib\UtilScreen.pas',
  BTSAISIECONSOMOB_TOF in '..\Mobilite\Lib\BTSAISIECONSOMOB_TOF.pas',
  BTRECHMOB_TOF in '..\Mobilite\Lib\BTRECHMOB_TOF.pas',
  ULiquidTva2014 in '..\LibBTP\ULiquidTva2014.pas',
  BTSIGNATURE_TOF in '..\Mobilite\Lib\BTSIGNATURE_TOF.PAS',
  Edisys_IULM_CoreEvents in '..\..\SPIGAO\EVENTS\Edisys_IULM_CoreEvents.pas',
  UtilPMAPCalcul in '..\LibBTP\UtilPMAPCalcul.pas',
  USeriaLSE in '..\..\ControleValidite\lib\USeriaLSE.pas',
  BTIMPORTBSV_TOF in '..\..\ImportBSV\Lib\BTIMPORTBSV_TOF.PAS',
  UXMLvalidation in '..\..\ImportBSV\Lib\UXMLvalidation.pas',
  MSXML2_TLB in '..\..\ImportBSV\Lib\MSXML2_TLB.pas',
  UImportFacXml in '..\..\ImportBSV\Lib\UImportFacXml.pas',
  BTIMPORTMULBSV_TOF in '..\..\ImportBSV\Lib\BTIMPORTMULBSV_TOF.PAS',
  PGInitRemDSN in '..\..\paie\lib\PGInitRemDSN.pas',
  SAISIEINV_MUL_TOF in '..\LibBTP\SAISIEINV_MUL_TOF.PAS',
  BTDUPLICINVENT_TOF in '..\LibBTP\BTDUPLICINVENT_TOF.PAS',
  BTRechargeFamTarif in '..\LibBTP\BTRechargeFamTarif.pas',
  BTSFAMTARIF_TOF in '..\LibBTP\BTSFAMTARIF_TOF.pas',
  TOMBTSOUSFAMILLETARIF in '..\LibBTP\TOMBTSOUSFAMILLETARIF.pas';

// FIN NEW

{$R *.RES}

begin
{$ifdef MEMCHECK}
  MemCheckLogFileName:=ChangeFileExt(Application.exename,'.log');
  MemChk;
{$endif}
  Application.Initialize;
  InitAgl;
  Application.Title := 'Mobilite';
  Application.CreateForm(TFMenuG, FMenuG);
  Application.CreateForm(TFMenuDisp, FMenuDisp);
  initApplication ;
  SplashScreen:=Nil ;
  if ParamCount=0 then
     BEGIN
     SplashScreen:=TSplashScreen.Create(Application) ;
     SplashScreen.Show ;
     SplashScreen.Update ;
     END ;
  Application.Run ;
end.
